//! Built-in APT group catalog (MITRE ATT&CK group IDs, aliases, and
//! associated malware families). Selecting a group expands into all of its
//! search terms, which the CompiledFilter matches against rule content.
//!
//! Generated from the official MITRE CTI STIX bundle (every non-deprecated,
//! non-revoked enterprise-attack intrusion-set), so it is offline and
//! covers every group MITRE tracks. `origin` is left blank for groups where
//! STIX does not carry a clean sponsor/region tag; aliases and MITRE ID
//! still make the group findable via search.

pub struct AptGroup {
    /// MITRE ATT&CK group id, e.g. "G0007"
    pub mitre_id: &'static str,
    /// Primary name shown in the UI
    pub name: &'static str,
    /// Aliases (also matched)
    pub aliases: &'static [&'static str],
    /// Malware / tool families attributed to the group (also matched)
    pub software: &'static [&'static str],
    /// Sponsor / region tag shown in UI to help picking
    pub origin: &'static str,
}

impl AptGroup {
    /// All search terms this group expands to.
    pub fn terms(&self) -> Vec<String> {
        let mut t: Vec<String> = Vec::new();
        t.push(self.name.to_string());
        t.extend(self.aliases.iter().map(|s| s.to_string()));
        t.extend(self.software.iter().map(|s| s.to_string()));
        t
    }

    /// Does a search string match this group's name/aliases/id?
    pub fn matches_search(&self, needle_lower: &str) -> bool {
        if needle_lower.is_empty() {
            return true;
        }
        self.mitre_id.to_lowercase().contains(needle_lower)
            || self.name.to_lowercase().contains(needle_lower)
            || self.origin.to_lowercase().contains(needle_lower)
            || self
                .aliases
                .iter()
                .any(|a| a.to_lowercase().contains(needle_lower))
    }
}

pub static APT_GROUPS: &[AptGroup] = &[
    AptGroup {
        mitre_id: "G0001",
        name: "Axiom",
        aliases: &["Group 72"],
        software: &[
            "Derusbi",
            "Hikit",
            "Hydraq",
            "PlugX",
            "PoisonIvy",
            "Zox",
            "ZxShell",
            "gh0st RAT",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0002",
        name: "Moafee",
        aliases: &[],
        software: &["PoisonIvy"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0003",
        name: "Cleaver",
        aliases: &["Threat Group 2889", "TG-2889"],
        software: &["Mimikatz", "Net Crawler", "PsExec", "TinyZBot"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0004",
        name: "Ke3chang",
        aliases: &[
            "APT15",
            "Mirage",
            "Vixen Panda",
            "GREF",
            "Playful Dragon",
            "RoyalAPT",
            "NICKEL",
            "Nylon Typhoon",
        ],
        software: &[
            "Mimikatz",
            "MirageFox",
            "Neoichor",
            "Net",
            "Okrum",
            "Ping",
            "Systeminfo",
            "Tasklist",
            "ipconfig",
            "netstat",
            "spwebmember",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0005",
        name: "APT12",
        aliases: &["IXESHE", "DynCalc", "Numbered Panda", "DNSCALC"],
        software: &["HTRAN", "Ixeshe", "RIPTIDE"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0006",
        name: "APT1",
        aliases: &["Comment Crew", "Comment Group", "Comment Panda"],
        software: &[
            "BISCUIT",
            "CALENDAR",
            "Cachedump",
            "GLOOXMAIL",
            "Lslsass",
            "Mimikatz",
            "Net",
            "Pass-The-Hash Toolkit",
            "PoisonIvy",
            "PsExec",
            "Seasalt",
            "Tasklist",
            "WEBC2",
            "gsecdump",
            "ipconfig",
            "pwdump",
            "xCmd",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0007",
        name: "APT28",
        aliases: &[
            "IRON TWILIGHT",
            "SNAKEMACKEREL",
            "Swallowtail",
            "Group 74",
            "Sednit",
            "Sofacy",
            "Pawn Storm",
            "Fancy Bear",
            "STRONTIUM",
            "Tsar Team",
            "Threat Group-4127",
            "TG-4127",
            "Forest Blizzard",
            "FROZENLAKE",
            "GruesomeLarch",
        ],
        software: &[
            "ADVSTORESHELL",
            "CHOPSTICK",
            "CORESHELL",
            "Cannon",
            "DealersChoice",
            "Downdelph",
            "Drovorub",
            "Forfiles",
            "Fysbis",
            "HIDEDRV",
            "JHUHUGIT",
            "Koadic",
            "Komplex",
            "LAMEHUG",
            "LoJax",
            "Mimikatz",
            "Net",
            "OLDBAIT",
            "Responder",
            "Tor",
            "USBStealer",
            "Wevtutil",
            "Winexe",
            "XAgentOSX",
            "XTunnel",
            "Zebrocy",
            "certutil",
            "cipher.exe",
            "reGeorg",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0008",
        name: "Carbanak",
        aliases: &["Anunak"],
        software: &["Carbanak", "Mimikatz", "PsExec", "netsh"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0009",
        name: "Deep Panda",
        aliases: &[
            "Shell Crew",
            "WebMasters",
            "KungFu Kittens",
            "PinkPanther",
            "Black Vine",
        ],
        software: &[
            "Derusbi", "Mivast", "Net", "Ping", "Sakula", "StreamEx", "Tasklist",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0010",
        name: "Turla",
        aliases: &[
            "IRON HUNTER",
            "Group 88",
            "Waterbug",
            "WhiteBear",
            "Snake",
            "Krypton",
            "Venomous Bear",
            "Secret Blizzard",
            "BELUGASTURGEON",
        ],
        software: &[
            "Arp",
            "Carbon",
            "ComRAT",
            "Crutch",
            "Empire",
            "Epic",
            "Gazer",
            "HyperStack",
            "IronNetInjector",
            "KOPILUWAK",
            "Kazuar",
            "LightNeuron",
            "LunarLoader",
            "LunarMail",
            "LunarWeb",
            "Mimikatz",
            "Mosquito",
            "NBTscan",
            "Net",
            "Penquin",
            "PowerStallion",
            "PsExec",
            "Reg",
            "Systeminfo",
            "Tasklist",
            "TinyTurla",
            "Uroburos",
            "certutil",
            "nbtstat",
            "netstat",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0011",
        name: "PittyTiger",
        aliases: &[],
        software: &["Lurid", "Mimikatz", "PoisonIvy", "gh0st RAT", "gsecdump"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0012",
        name: "Darkhotel",
        aliases: &["DUBNIUM", "Zigzag Hail"],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0013",
        name: "APT30",
        aliases: &[],
        software: &[
            "BACKSPACE",
            "FLASHFLOOD",
            "NETEAGLE",
            "SHIPSHAPE",
            "SPACESHIP",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0016",
        name: "APT29",
        aliases: &[
            "IRON RITUAL",
            "IRON HEMLOCK",
            "NobleBaron",
            "Dark Halo",
            "NOBELIUM",
            "UNC2452",
            "YTTRIUM",
            "The Dukes",
            "Cozy Bear",
            "CozyDuke",
            "SolarStorm",
            "Blue Kitsune",
            "UNC3524",
            "Midnight Blizzard",
        ],
        software: &[
            "AADInternals",
            "AdFind",
            "BloodHound",
            "BoomBox",
            "CloudDuke",
            "Cobalt Strike",
            "CosmicDuke",
            "CozyCar",
            "EnvyScout",
            "FatDuke",
            "FoggyWeb",
            "GeminiDuke",
            "GoldFinder",
            "GoldMax",
            "HAMMERTOSS",
            "Impacket",
            "LiteDuke",
            "Mimikatz",
            "MiniDuke",
            "NativeZone",
            "Net",
            "OnionDuke",
            "POSHSPY",
            "PinchDuke",
            "PolyglotDuke",
            "PowerDuke",
            "PsExec",
            "QUIETEXIT",
            "ROADTools",
            "Raindrop",
            "RegDuke",
            "SDelete",
            "SUNBURST",
            "SUNSPOT",
            "SeaDuke",
            "Sibot",
            "Sliver",
            "SoreFang",
            "Systeminfo",
            "TEARDROP",
            "Tasklist",
            "Tor",
            "TrailBlazer",
            "VaporRage",
            "WellMail",
            "WellMess",
            "ipconfig",
            "meek",
            "reGeorg",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0017",
        name: "DragonOK",
        aliases: &[],
        software: &["PlugX", "PoisonIvy"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0018",
        name: "admin@338",
        aliases: &[],
        software: &[
            "BUBBLEWRAP",
            "LOWBALL",
            "Net",
            "PoisonIvy",
            "Systeminfo",
            "ipconfig",
            "netstat",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0019",
        name: "Naikon",
        aliases: &[],
        software: &[
            "Aria-body",
            "HDoor",
            "Nebulae",
            "Net",
            "Ping",
            "PsExec",
            "RARSTONE",
            "RainyDay",
            "SslMM",
            "Sys10",
            "Systeminfo",
            "Tasklist",
            "WinMM",
            "ftp",
            "netsh",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0020",
        name: "Equation",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0021",
        name: "Molerats",
        aliases: &["Operation Molerats", "Gaza Cybergang"],
        software: &[
            "DropBook",
            "DustySky",
            "MoleNet",
            "PoisonIvy",
            "SharpStage",
            "Spark",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0022",
        name: "APT3",
        aliases: &[
            "Gothic Panda",
            "Pirpi",
            "UPS Team",
            "Buckeye",
            "Threat Group-0110",
            "TG-0110",
        ],
        software: &[
            "LaZagne",
            "OSInfo",
            "PlugX",
            "RemoteCMD",
            "SHOTPUT",
            "schtasks",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0023",
        name: "APT16",
        aliases: &[],
        software: &["ELMER"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0024",
        name: "Putter Panda",
        aliases: &["APT2", "MSUpdater"],
        software: &["3PARA RAT", "4H RAT", "httpclient", "pngdowner"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0025",
        name: "APT17",
        aliases: &["Deputy Dog"],
        software: &["BLACKCOFFEE"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0026",
        name: "APT18",
        aliases: &["TG-0416", "Dynamite Panda", "Threat Group-0416"],
        software: &["HTTPBrowser", "Pisloader", "cmd", "gh0st RAT", "hcdLoader"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0027",
        name: "Threat Group-3390",
        aliases: &[
            "Earth Smilodon",
            "TG-3390",
            "Emissary Panda",
            "BRONZE UNION",
            "APT27",
            "Iron Tiger",
            "LuckyMouse",
            "Linen Typhoon",
        ],
        software: &[
            "ASPXSpy",
            "China Chopper",
            "Clambling",
            "Cobalt Strike",
            "HTTPBrowser",
            "HyperBro",
            "Impacket",
            "Mimikatz",
            "NBTscan",
            "Net",
            "Pandora",
            "PlugX",
            "RCSession",
            "SysUpdate",
            "Systeminfo",
            "Tasklist",
            "Windows Credential Editor",
            "ZxShell",
            "certutil",
            "gh0st RAT",
            "gsecdump",
            "ipconfig",
            "netstat",
            "pwdump",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0028",
        name: "Threat Group-1314",
        aliases: &["TG-1314"],
        software: &["Net", "PsExec"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0029",
        name: "Scarlet Mimic",
        aliases: &[],
        software: &["CallMe", "FakeM", "MobileOrder", "Psylo"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0030",
        name: "Lotus Blossom",
        aliases: &[
            "DRAGONFISH",
            "Spring Dragon",
            "RADIUM",
            "Raspberry Typhoon",
            "Bilbug",
            "Thrip",
        ],
        software: &[
            "AdFind",
            "Elise",
            "Emissary",
            "Hannotog",
            "Impacket",
            "NBTscan",
            "Ping",
            "Sagerunex",
            "certutil",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0032",
        name: "Lazarus Group",
        aliases: &[
            "Labyrinth Chollima",
            "HIDDEN COBRA",
            "Guardians of Peace",
            "ZINC",
            "NICKEL ACADEMY",
            "Diamond Sleet",
        ],
        software: &[
            "AppleJeus",
            "AuditCred",
            "BADCALL",
            "BLINDINGCAN",
            "Bankshot",
            "Cryptoistic",
            "Dacls",
            "Dtrack",
            "ECCENTRICBANDWAGON",
            "FALLCHILL",
            "HARDRAIN",
            "HOPLIGHT",
            "HotCroissant",
            "KEYMARBLE",
            "MagicRAT",
            "Proxysvc",
            "RATANKBA",
            "RawDisk",
            "Responder",
            "TAINTEDSCRIBE",
            "TYPEFRAME",
            "ThreatNeedle",
            "Volgmer",
            "WannaCry",
            "netsh",
            "route",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0033",
        name: "Poseidon Group",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0034",
        name: "Sandworm Team",
        aliases: &[
            "ELECTRUM",
            "Telebots",
            "IRON VIKING",
            "BlackEnergy (Group)",
            "Quedagh",
            "Voodoo Bear",
            "IRIDIUM",
            "Seashell Blizzard",
            "FROZENBARENTS",
            "APT44",
        ],
        software: &[
            "AcidPour",
            "AcidRain",
            "Bad Rabbit",
            "BlackEnergy",
            "Cobalt Strike",
            "Cyclops Blink",
            "Empire",
            "Exaramel for Linux",
            "Exaramel for Windows",
            "GreyEnergy",
            "Impacket",
            "Industroyer",
            "Industroyer2",
            "Invoke-PSImage",
            "Kapeka",
            "KillDisk",
            "Mimikatz",
            "Neo-reGeorg",
            "Net",
            "NotPetya",
            "Olympic Destroyer",
            "P.A.S. Webshell",
            "PoshC2",
            "Prestige",
            "PsExec",
            "SDelete",
            "VPNFilter",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0035",
        name: "Dragonfly",
        aliases: &[
            "TEMP.Isotope",
            "DYMALLOY",
            "Berserk Bear",
            "TG-4192",
            "Crouching Yeti",
            "IRON LIBERTY",
            "Energetic Bear",
            "Ghost Blizzard",
            "BROMINE",
        ],
        software: &[
            "Backdoor.Oldrea",
            "CrackMapExec",
            "Impacket",
            "MCMD",
            "Mimikatz",
            "Net",
            "PsExec",
            "Reg",
            "Trojan.Karagany",
            "netsh",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0036",
        name: "GCMAN",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0037",
        name: "FIN6",
        aliases: &[
            "Magecart Group 6",
            "ITG08",
            "Skeleton Spider",
            "TAAL",
            "Camouflage Tempest",
        ],
        software: &[
            "AdFind",
            "Cobalt Strike",
            "FlawedAmmyy",
            "FrameworkPOS",
            "GrimAgent",
            "LockerGoga",
            "Maze",
            "Mimikatz",
            "More_eggs",
            "PsExec",
            "Ryuk",
            "Windows Credential Editor",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0038",
        name: "Stealth Falcon",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0039",
        name: "Suckfly",
        aliases: &[],
        software: &["Nidiran"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0040",
        name: "Patchwork",
        aliases: &[
            "Hangover Group",
            "Dropping Elephant",
            "Chinastrats",
            "MONSOON",
            "Operation Hangover",
        ],
        software: &[
            "AutoIt backdoor",
            "BADNEWS",
            "BackConfig",
            "NDiskMonitor",
            "PowerSploit",
            "QuasarRAT",
            "TINYTYPHON",
            "Unknown Logger",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0041",
        name: "Strider",
        aliases: &["ProjectSauron"],
        software: &["Remsec"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0043",
        name: "Group5",
        aliases: &[],
        software: &["NanoCore", "njRAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0044",
        name: "Winnti Group",
        aliases: &["Blackfly"],
        software: &["PipeMon", "PlugX", "Winnti for Windows"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0045",
        name: "menuPass",
        aliases: &[
            "Cicada",
            "POTASSIUM",
            "Stone Panda",
            "APT10",
            "Red Apollo",
            "CVNX",
            "HOGFISH",
            "BRONZE RIVERSIDE",
        ],
        software: &[
            "AdFind",
            "ChChes",
            "Cobalt Strike",
            "Ecipekac",
            "EvilGrab",
            "FYAnti",
            "HUI Loader",
            "Impacket",
            "Mimikatz",
            "Net",
            "P8RAT",
            "Ping",
            "PlugX",
            "PoisonIvy",
            "PowerSploit",
            "PsExec",
            "QuasarRAT",
            "RedLeaves",
            "SNUGRIDE",
            "SodaMaster",
            "UPPERCUT",
            "certutil",
            "cmd",
            "esentutl",
            "pwdump",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0046",
        name: "FIN7",
        aliases: &[
            "GOLD NIAGARA",
            "ITG14",
            "Carbon Spider",
            "ELBRUS",
            "Sangria Tempest",
        ],
        software: &[
            "AdFind",
            "BOOSTWRITE",
            "Carbanak",
            "Cobalt Strike",
            "CrackMapExec",
            "GRIFFON",
            "HALFBAKED",
            "JSS Loader",
            "Lizar",
            "Maze",
            "Mimikatz",
            "POWERSOURCE",
            "Pillowmint",
            "PowerSploit",
            "RDFSNIFFER",
            "REvil",
            "SQLRat",
            "SystemBC",
            "TEXTMATE",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0047",
        name: "Gamaredon Group",
        aliases: &[
            "IRON TILDEN",
            "Primitive Bear",
            "ACTINIUM",
            "Armageddon",
            "Shuckworm",
            "DEV-0157",
            "Aqua Blizzard",
            "NastyShrew",
        ],
        software: &[
            "Ping",
            "PowerPunch",
            "Pteranodon",
            "QuietSieve",
            "Reg",
            "Remcos",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0048",
        name: "RTM",
        aliases: &[],
        software: &["RTM"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0049",
        name: "OilRig",
        aliases: &[
            "COBALT GYPSY",
            "IRN2",
            "APT34",
            "Helix Kitten",
            "Evasive Serpens",
            "Hazel Sandstorm",
            "EUROPIUM",
            "ITG13",
            "Earth Simnavaz",
            "Crambus",
            "TA452",
        ],
        software: &[
            "BONDUPDATER",
            "Helminth",
            "ISMInjector",
            "LaZagne",
            "Mango",
            "Mimikatz",
            "Net",
            "ODAgent",
            "OilBooster",
            "OilCheck",
            "OopsIE",
            "POWRUNER",
            "PowerExchange",
            "PsExec",
            "QUADAGENT",
            "RDAT",
            "RGDoor",
            "Reg",
            "SEASHARPEE",
            "SampleCheck5000",
            "SideTwist",
            "Solar",
            "Systeminfo",
            "Tasklist",
            "ZeroCleare",
            "certutil",
            "ftp",
            "ipconfig",
            "netstat",
            "ngrok",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0050",
        name: "APT32",
        aliases: &[
            "SeaLotus",
            "OceanLotus",
            "APT-C-00",
            "Canvas Cyclone",
            "BISMUTH",
        ],
        software: &[
            "Arp",
            "Cobalt Strike",
            "Denis",
            "Goopy",
            "KOMPROGO",
            "Kerrdown",
            "Mimikatz",
            "Net",
            "OSX_OCEANLOTUS.D",
            "PHOREAL",
            "RotaJakiro",
            "SOUNDBITE",
            "WINDSHIELD",
            "ipconfig",
            "netsh",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0051",
        name: "FIN10",
        aliases: &[],
        software: &["Empire"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0052",
        name: "CopyKittens",
        aliases: &[],
        software: &["Cobalt Strike", "Empire", "Matryoshka", "TDTESS"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0053",
        name: "FIN5",
        aliases: &[],
        software: &[
            "FLIPSIDE",
            "PsExec",
            "RawPOS",
            "SDelete",
            "Windows Credential Editor",
            "pwdump",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0054",
        name: "Sowbug",
        aliases: &[],
        software: &["Felismus", "Starloader"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0055",
        name: "NEODYMIUM",
        aliases: &[],
        software: &["Wingbird"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0056",
        name: "PROMETHIUM",
        aliases: &["StrongPity"],
        software: &["StrongPity", "Truvasys"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0059",
        name: "Magic Hound",
        aliases: &[
            "TA453",
            "COBALT ILLUSION",
            "Charming Kitten",
            "ITG18",
            "Phosphorus",
            "Newscaster",
            "APT35",
            "Mint Sandstorm",
        ],
        software: &[
            "CharmPower",
            "DownPaper",
            "FRP",
            "Impacket",
            "Mimikatz",
            "Net",
            "Ping",
            "PowerLess",
            "PsExec",
            "Pupy",
            "Systeminfo",
            "ipconfig",
            "netsh",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0060",
        name: "BRONZE BUTLER",
        aliases: &["REDBALDKNIGHT", "Tick"],
        software: &[
            "ABK",
            "Avenger",
            "BBK",
            "Daserf",
            "Mimikatz",
            "Net",
            "ShadowPad",
            "Windows Credential Editor",
            "at",
            "build_downer",
            "cmd",
            "down_new",
            "gsecdump",
            "schtasks",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0061",
        name: "FIN8",
        aliases: &["Syssphinx"],
        software: &[
            "BADHATCH",
            "Impacket",
            "Net",
            "Nltest",
            "PUNCHBUGGY",
            "PUNCHTRACK",
            "Ping",
            "PsExec",
            "Ragnar Locker",
            "Sardonic",
            "dsquery",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0062",
        name: "TA459",
        aliases: &[],
        software: &["NetTraveler", "PlugX", "ZeroT", "gh0st RAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0063",
        name: "BlackOasis",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0064",
        name: "APT33",
        aliases: &["HOLMIUM", "Elfin", "Peach Sandstorm"],
        software: &[
            "AutoIt backdoor",
            "DEADWOOD",
            "Empire",
            "LaZagne",
            "Mimikatz",
            "NETWIRE",
            "NanoCore",
            "Net",
            "POWERTON",
            "PoshC2",
            "PowerSploit",
            "Pupy",
            "Ruler",
            "StoneDrill",
            "TURNEDUP",
            "ftp",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0065",
        name: "Leviathan",
        aliases: &[
            "MUDCARP",
            "Kryptonite Panda",
            "Gadolinium",
            "BRONZE MOHAWK",
            "TEMP.Jumper",
            "APT40",
            "TEMP.Periscope",
            "Gingham Typhoon",
        ],
        software: &[
            "BADFLICK",
            "BITSAdmin",
            "BLACKCOFFEE",
            "China Chopper",
            "Cobalt Strike",
            "Derusbi",
            "Empire",
            "HOMEFRY",
            "MURKYTOP",
            "NanHaiShu",
            "Net",
            "Orz",
            "PowerSploit",
            "Tor",
            "Windows Credential Editor",
            "at",
            "gh0st RAT",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0066",
        name: "Elderwood",
        aliases: &["Elderwood Gang", "Beijing Group", "Sneaky Panda"],
        software: &[
            "Briba",
            "Hydraq",
            "Linfo",
            "Naid",
            "Nerex",
            "Pasam",
            "PoisonIvy",
            "Vasport",
            "Wiarp",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0067",
        name: "APT37",
        aliases: &[
            "InkySquid",
            "ScarCruft",
            "Reaper",
            "Group123",
            "TEMP.Reaper",
            "Ricochet Chollima",
        ],
        software: &[
            "BLUELIGHT",
            "CORALDECK",
            "Cobalt Strike",
            "DOGCALL",
            "Final1stspy",
            "HAPPYWORK",
            "KARAE",
            "NavRAT",
            "POORAIM",
            "ROKRAT",
            "SHUTTERSPEED",
            "SLOWDRIFT",
            "WINERACK",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0068",
        name: "PLATINUM",
        aliases: &[],
        software: &["Dipsind", "JPIN", "adbupd"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0069",
        name: "MuddyWater",
        aliases: &[
            "Earth Vetala",
            "MERCURY",
            "Static Kitten",
            "Seedworm",
            "TEMP.Zagros",
            "Mango Sandstorm",
            "TA450",
            "MuddyKrill",
        ],
        software: &[
            "ConnectWise",
            "CrackMapExec",
            "Empire",
            "Fooder",
            "Koadic",
            "LP-Notes",
            "LaZagne",
            "Mimikatz",
            "Mori",
            "MuddyViper",
            "Out1",
            "POWERSTATS",
            "PowGoop",
            "PowerSploit",
            "Rclone",
            "RemoteUtilities",
            "RustyWater",
            "SHARPSTATS",
            "STARWHALE",
            "Small Sieve",
            "Tsundere Botnet",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0070",
        name: "Dark Caracal",
        aliases: &[],
        software: &["Bandook", "CrossRAT", "FinFisher"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0071",
        name: "Orangeworm",
        aliases: &[],
        software: &[
            "Arp",
            "Kwampirs",
            "Net",
            "Systeminfo",
            "cmd",
            "ipconfig",
            "netstat",
            "route",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0073",
        name: "APT19",
        aliases: &["Codoso", "C0d0so0", "Codoso Team", "Sunshop Group"],
        software: &["Cobalt Strike", "Empire"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0075",
        name: "Rancor",
        aliases: &[],
        software: &["DDKONG", "PLAINTEE", "Reg", "certutil"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0076",
        name: "Thrip",
        aliases: &[],
        software: &["Catchamas", "Mimikatz", "PsExec"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0077",
        name: "Leafminer",
        aliases: &["Raspite"],
        software: &["LaZagne", "MailSniper", "Mimikatz", "PsExec"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0078",
        name: "Gorgon Group",
        aliases: &[],
        software: &["NanoCore", "QuasarRAT", "Remcos", "njRAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0079",
        name: "DarkHydrus",
        aliases: &[],
        software: &["Cobalt Strike", "Mimikatz", "RogueRobin"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0080",
        name: "Cobalt Group",
        aliases: &["GOLD KINGSWOOD", "Cobalt Gang", "Cobalt Spider"],
        software: &[
            "Cobalt Strike",
            "Mimikatz",
            "More_eggs",
            "PsExec",
            "SDelete",
            "SpicyOmelette",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0081",
        name: "Tropic Trooper",
        aliases: &["Pirate Panda", "KeyBoy"],
        software: &[
            "BITSAdmin",
            "KeyBoy",
            "PoisonIvy",
            "ShadowPad",
            "USBferry",
            "YAHOYAH",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0082",
        name: "APT38",
        aliases: &[
            "NICKEL GLADSTONE",
            "BeagleBoyz",
            "Bluenoroff",
            "Stardust Chollima",
            "Sapphire Sleet",
            "COPERNICIUM",
        ],
        software: &[
            "DarkComet",
            "ECCENTRICBANDWAGON",
            "HOPLIGHT",
            "KillDisk",
            "Mimikatz",
            "Net",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0083",
        name: "SilverTerrier",
        aliases: &[],
        software: &["Agent Tesla", "DarkComet", "Lokibot", "NETWIRE", "NanoCore"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0084",
        name: "Gallmaker",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0085",
        name: "FIN4",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0087",
        name: "APT39",
        aliases: &["ITG07", "Chafer", "Remix Kitten"],
        software: &[
            "ASPXSpy",
            "Cadelspy",
            "CrackMapExec",
            "MechaFlounder",
            "Mimikatz",
            "NBTscan",
            "PsExec",
            "Remexi",
            "Windows Credential Editor",
            "ftp",
            "pwdump",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0088",
        name: "TEMP.Veles",
        aliases: &["XENOTIME"],
        software: &["Mimikatz", "PsExec"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0089",
        name: "The White Company",
        aliases: &[],
        software: &["NETWIRE", "Revenge RAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0090",
        name: "WIRTE",
        aliases: &["Ashen Lepus"],
        software: &[
            "AshTag",
            "Empire",
            "Ferocious",
            "Havoc",
            "IronWind",
            "LitePower",
            "Rclone",
            "SameCoin",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0091",
        name: "Silence",
        aliases: &["Whisper Spider"],
        software: &["Empire", "SDelete", "Winexe"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0092",
        name: "TA505",
        aliases: &["Hive0065", "Spandex Tempest", "CHIMBORAZO"],
        software: &[
            "AdFind",
            "Amadey",
            "Azorult",
            "BloodHound",
            "Clop",
            "Cobalt Strike",
            "Dridex",
            "FlawedAmmyy",
            "FlawedGrace",
            "Get2",
            "Mimikatz",
            "Net",
            "PowerSploit",
            "SDBbot",
            "ServHelper",
            "TrickBot",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0093",
        name: "GALLIUM",
        aliases: &["Granite Typhoon"],
        software: &[
            "BlackMould",
            "China Chopper",
            "HTRAN",
            "Mimikatz",
            "NBTscan",
            "Net",
            "Ping",
            "PingPull",
            "PlugX",
            "PoisonIvy",
            "PsExec",
            "Reg",
            "Windows Credential Editor",
            "at",
            "cmd",
            "ipconfig",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0094",
        name: "Kimsuky",
        aliases: &[
            "Black Banshee",
            "Velvet Chollima",
            "Emerald Sleet",
            "THALLIUM",
            "APT43",
            "TA427",
            "Springtail",
            "Earth Kumiho",
            "PatheticSlug",
        ],
        software: &[
            "Amadey",
            "AppleSeed",
            "BabyShark",
            "Brave Prince",
            "CSPY Downloader",
            "GoBear",
            "Gold Dragon",
            "Gomir",
            "HTTPTroy",
            "KGH_SPY",
            "Mimikatz",
            "NOKKI",
            "PsExec",
            "QuasarRAT",
            "TRANSLATEXT",
            "Troll Stealer",
            "certutil",
            "gh0st RAT",
            "schtasks",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0095",
        name: "Machete",
        aliases: &["APT-C-43", "El Machete"],
        software: &["Machete"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0096",
        name: "APT41",
        aliases: &["Wicked Panda", "Brass Typhoon", "BARIUM"],
        software: &[
            "ASPXSpy",
            "BITSAdmin",
            "BLACKCOFFEE",
            "China Chopper",
            "Cobalt Strike",
            "DUSTPAN",
            "DUSTTRAP",
            "Derusbi",
            "Empire",
            "Impacket",
            "KEYPLUG",
            "LightSpy",
            "MESSAGETAP",
            "MOPSLED",
            "Mimikatz",
            "Net",
            "Ping",
            "PlugX",
            "PowerSploit",
            "ROCKBOOT",
            "ShadowPad",
            "Winnti for Linux",
            "ZxShell",
            "certutil",
            "dsquery",
            "ftp",
            "gh0st RAT",
            "ipconfig",
            "netstat",
            "njRAT",
            "pwdump",
            "sqlmap",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0098",
        name: "BlackTech",
        aliases: &["Palmerworm"],
        software: &[
            "Flagpro",
            "Kivars",
            "PLEAD",
            "PsExec",
            "TSCookie",
            "Waterbear",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0099",
        name: "APT-C-36",
        aliases: &["Blind Eagle", "TAG-144", "AguilaCiega", "APT-Q-98"],
        software: &[
            "AsyncRAT",
            "Caminho",
            "DCRAT",
            "HeartCrypt",
            "Imminent Monitor",
            "PureCrypter",
            "QuasarRAT",
            "Remcos",
            "njRAT",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0100",
        name: "Inception",
        aliases: &["Inception Framework", "Cloud Atlas"],
        software: &["LaZagne", "PowerShower", "VBShower"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0102",
        name: "Wizard Spider",
        aliases: &[
            "UNC1878",
            "TEMP.MixMaster",
            "Grim Spider",
            "FIN12",
            "GOLD BLACKBURN",
            "ITG23",
            "Periwinkle Tempest",
            "DEV-0193",
            "Pistachio Tempest",
            "DEV-0237",
        ],
        software: &[
            "AdFind",
            "Anchor",
            "BITSAdmin",
            "Bazar",
            "BloodHound",
            "Cobalt Strike",
            "Conti",
            "Diavol",
            "Dyre",
            "Emotet",
            "Empire",
            "GrimAgent",
            "LaZagne",
            "Mimikatz",
            "Net",
            "Nltest",
            "Ping",
            "PsExec",
            "Rubeus",
            "Ryuk",
            "SystemBC",
            "TrickBot",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0103",
        name: "Mofang",
        aliases: &[],
        software: &["ShimRat", "ShimRatReporter"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0105",
        name: "DarkVishnya",
        aliases: &[],
        software: &["PsExec", "Winexe"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0106",
        name: "Rocke",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0107",
        name: "Whitefly",
        aliases: &[],
        software: &["Mimikatz"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0108",
        name: "Blue Mockingbird",
        aliases: &[],
        software: &["FRP", "Mimikatz"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0112",
        name: "Windshift",
        aliases: &["Bahamut"],
        software: &["WindTail"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0114",
        name: "Chimera",
        aliases: &[],
        software: &[
            "BloodHound",
            "Cobalt Strike",
            "Mimikatz",
            "Net",
            "PsExec",
            "esentutl",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0115",
        name: "GOLD SOUTHFIELD",
        aliases: &["Pinchy Spider"],
        software: &["ConnectWise", "REvil"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0117",
        name: "Fox Kitten",
        aliases: &[
            "UNC757",
            "Parisite",
            "Pioneer Kitten",
            "RUBIDIUM",
            "Lemon Sandstorm",
        ],
        software: &["China Chopper", "Pay2Key", "PsExec", "SystemBC", "ngrok"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0119",
        name: "Indrik Spider",
        aliases: &["Evil Corp", "Manatee Tempest", "DEV-0243", "UNC2165"],
        software: &[
            "BitPaymer",
            "Cobalt Strike",
            "Donut",
            "Dridex",
            "Empire",
            "Mimikatz",
            "PsExec",
            "WastedLocker",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0120",
        name: "Evilnum",
        aliases: &[],
        software: &["EVILNUM", "LaZagne", "More_eggs"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0121",
        name: "Sidewinder",
        aliases: &["T-APT-04", "Rattlesnake"],
        software: &["Koadic"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0122",
        name: "Silent Librarian",
        aliases: &["TA407", "COBALT DICKENS"],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0123",
        name: "Volatile Cedar",
        aliases: &["Lebanese Cedar"],
        software: &["Caterpillar WebShell", "Explosive"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0124",
        name: "Windigo",
        aliases: &[],
        software: &["Ebury"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0125",
        name: "HAFNIUM",
        aliases: &["Operation Exchange Marauder", "Silk Typhoon"],
        software: &[
            "ASPXSpy",
            "China Chopper",
            "Covenant",
            "Impacket",
            "PsExec",
            "Tarrask",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0126",
        name: "Higaisa",
        aliases: &[],
        software: &["PlugX", "certutil", "gh0st RAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0127",
        name: "TA551",
        aliases: &["GOLD CABIN", "Shathak"],
        software: &["IcedID", "QakBot", "Sliver", "Ursnif", "Valak"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0128",
        name: "ZIRCONIUM",
        aliases: &["APT31", "Violet Typhoon"],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0129",
        name: "Mustang Panda",
        aliases: &[
            "TA416",
            "RedDelta",
            "BRONZE PRESIDENT",
            "STATELY TAURUS",
            "FIREANT",
            "CAMARO DRAGON",
            "EARTH PRETA",
            "HIVE0154",
            "TWILL TYPHOON",
            "TANTALUM",
            "LUMINOUS MOTH",
            "UNC6384",
            "TEMP.Hex",
            "Red Lich",
            "ClumsyToad",
        ],
        software: &[
            "AdFind",
            "BOOKWORM",
            "CANONSTAGER",
            "CLAIMLOADER",
            "China Chopper",
            "Cobalt Strike",
            "CorKLOG",
            "HIUPAN",
            "Impacket",
            "Mimikatz",
            "NBTscan",
            "PAKLOG",
            "PUBLOAD",
            "PlugX",
            "PoisonIvy",
            "RCSession",
            "STATICPLUGIN",
            "ShadowPad",
            "SplatCloak",
            "SplatDropper",
            "StarProxy",
            "TONESHELL",
            "Wevtutil",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0130",
        name: "Ajax Security Team",
        aliases: &[
            "Operation Woolen-Goldfish",
            "AjaxTM",
            "Rocket Kitten",
            "Flying Kitten",
            "Operation Saffron Rose",
        ],
        software: &["Havij", "sqlmap"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0131",
        name: "Tonto Team",
        aliases: &[
            "Earth Akhlut",
            "BRONZE HUNTLEY",
            "CactusPete",
            "Karma Panda",
        ],
        software: &[
            "Bisonal",
            "LaZagne",
            "Mimikatz",
            "NBTscan",
            "ShadowPad",
            "gsecdump",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0133",
        name: "Nomadic Octopus",
        aliases: &["DustSquad"],
        software: &["Octopus"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0134",
        name: "Transparent Tribe",
        aliases: &["COPPER FIELDSTONE", "APT36", "Mythic Leopard", "ProjectM"],
        software: &["Crimson", "DarkComet", "ObliqueRAT", "Peppy", "njRAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0135",
        name: "BackdoorDiplomacy",
        aliases: &[],
        software: &[
            "China Chopper",
            "Mimikatz",
            "NBTscan",
            "QuasarRAT",
            "Turian",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0136",
        name: "IndigoZebra",
        aliases: &[],
        software: &["BoxCaon", "PoisonIvy", "xCaon"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0137",
        name: "Ferocious Kitten",
        aliases: &[],
        software: &["BITSAdmin", "MarkiRAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0138",
        name: "Andariel",
        aliases: &["Silent Chollima", "PLUTONIUM", "Onyx Sleet"],
        software: &["Rifdoor", "gh0st RAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0139",
        name: "TeamTNT",
        aliases: &[],
        software: &["Hildegard", "LaZagne", "MimiPenguin", "Peirates"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0140",
        name: "LazyScripter",
        aliases: &[],
        software: &[
            "Empire",
            "KOCTOPUS",
            "Koadic",
            "QuasarRAT",
            "Remcos",
            "ngrok",
            "njRAT",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0142",
        name: "Confucius",
        aliases: &["Confucius APT"],
        software: &["WarzoneRAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G0143",
        name: "Aquatic Panda",
        aliases: &[],
        software: &[
            "Cobalt Strike",
            "ShadowPad",
            "Wevtutil",
            "Winnti for Linux",
            "Winnti for Windows",
            "njRAT",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1001",
        name: "HEXANE",
        aliases: &["Lyceum", "Siamesekitten", "Spirlin"],
        software: &[
            "BITSAdmin",
            "DanBot",
            "DnsSystem",
            "Empire",
            "Kevin",
            "Milan",
            "Mimikatz",
            "Ping",
            "PoshC2",
            "Shark",
            "ipconfig",
            "netstat",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1002",
        name: "BITTER",
        aliases: &["T-APT-17"],
        software: &["ZxxZ"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1003",
        name: "Ember Bear",
        aliases: &[
            "UNC2589",
            "Bleeding Bear",
            "DEV-0586",
            "Cadet Blizzard",
            "Frozenvista",
            "UAC-0056",
        ],
        software: &[
            "BloodHound",
            "CrackMapExec",
            "Impacket",
            "P.A.S. Webshell",
            "PsExec",
            "Rclone",
            "Responder",
            "Saint Bot",
            "WhisperGate",
            "ngrok",
            "reGeorg",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1004",
        name: "LAPSUS$",
        aliases: &["DEV-0537", "Strawberry Tempest"],
        software: &["Mimikatz"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1005",
        name: "POLONIUM",
        aliases: &["Plaid Rain"],
        software: &["CreepyDrive", "CreepySnail"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1006",
        name: "Earth Lusca",
        aliases: &["TAG-22", "Charcoal Typhoon", "CHROMIUM", "ControlX"],
        software: &[
            "Cobalt Strike",
            "Mimikatz",
            "NBTscan",
            "Nltest",
            "PowerSploit",
            "ShadowPad",
            "Tasklist",
            "Winnti for Linux",
            "certutil",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1007",
        name: "Aoqin Dragon",
        aliases: &[],
        software: &["Heyoka Backdoor", "Mongall"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1008",
        name: "SideCopy",
        aliases: &[],
        software: &["Action RAT", "AuTo Stealer"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1009",
        name: "Moses Staff",
        aliases: &["DEV-0500", "Marigold Sandstorm"],
        software: &["DCSrv", "PsExec", "PyDCrypt", "StrifeWater"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1011",
        name: "EXOTIC LILY",
        aliases: &[],
        software: &["Bazar", "Bumblebee"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1012",
        name: "CURIUM",
        aliases: &[
            "Crimson Sandstorm",
            "TA456",
            "Tortoise Shell",
            "Yellow Liderc",
        ],
        software: &["IMAPLoader"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1013",
        name: "Metador",
        aliases: &[],
        software: &["Mafalda", "metaMain"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1014",
        name: "LuminousMoth",
        aliases: &[],
        software: &["Cobalt Strike", "PlugX"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1015",
        name: "Scattered Spider",
        aliases: &["Roasted 0ktapus", "Octo Tempest", "Storm-0875", "UNC3944"],
        software: &[
            "BlackCat",
            "ConnectWise",
            "LaZagne",
            "Mimikatz",
            "Raccoon Stealer",
            "Rclone",
            "Tor",
            "WarzoneRAT",
            "ngrok",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1016",
        name: "FIN13",
        aliases: &["Elephant Beetle"],
        software: &["Empire", "Impacket", "Mimikatz", "certutil"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1017",
        name: "Volt Typhoon",
        aliases: &[
            "BRONZE SILHOUETTE",
            "Vanguard Panda",
            "DEV-0391",
            "UNC3236",
            "Voltzite",
            "Insidious Taurus",
            "DazedToad",
        ],
        software: &[
            "FRP",
            "Impacket",
            "Mimikatz",
            "Net",
            "Nltest",
            "Ping",
            "PsExec",
            "Reg",
            "Systeminfo",
            "Tasklist",
            "VersaMem",
            "Wevtutil",
            "certutil",
            "cmd",
            "ipconfig",
            "netsh",
            "netstat",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1018",
        name: "TA2541",
        aliases: &[],
        software: &[
            "Agent Tesla",
            "AsyncRAT",
            "Imminent Monitor",
            "NETWIRE",
            "Revenge RAT",
            "Snip3",
            "WarzoneRAT",
            "jRAT",
            "njRAT",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1019",
        name: "MoustachedBouncer",
        aliases: &[],
        software: &["Disco", "NightClub", "SharpDisco"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1020",
        name: "Mustard Tempest",
        aliases: &["DEV-0206", "TA569", "GOLD PRELUDE", "UNC1543"],
        software: &["Cobalt Strike", "SocGholish"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1021",
        name: "Cinnamon Tempest",
        aliases: &["DEV-0401", "Emperor Dragonfly", "BRONZE STARLIGHT"],
        software: &[
            "Cheerscrypt",
            "Cobalt Strike",
            "HUI Loader",
            "Impacket",
            "Pandora",
            "PlugX",
            "Rclone",
            "Sliver",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1022",
        name: "ToddyCat",
        aliases: &[],
        software: &[
            "China Chopper",
            "Cobalt Strike",
            "LoFiSe",
            "Net",
            "Ninja",
            "Pcexter",
            "Ping",
            "Samurai",
            "netstat",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1023",
        name: "APT5",
        aliases: &[
            "Mulberry Typhoon",
            "MANGANESE",
            "BRONZE FLEETWOOD",
            "Keyhole Panda",
            "UNC2630",
        ],
        software: &[
            "Mimikatz",
            "Net",
            "PACEMAKER",
            "PULSECHECK",
            "PcShare",
            "PoisonIvy",
            "RAPIDPULSE",
            "SLIGHTPULSE",
            "SLOWPULSE",
            "Skeleton Key",
            "Tasklist",
            "gh0st RAT",
            "netstat",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1024",
        name: "Akira",
        aliases: &["GOLD SAHARA", "PUNK SPIDER", "Howling Scorpius"],
        software: &[
            "AdFind",
            "Akira",
            "Akira _v2",
            "LaZagne",
            "Megazord",
            "Mimikatz",
            "PsExec",
            "Rclone",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1026",
        name: "Malteiro",
        aliases: &[],
        software: &["Mispadu"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1028",
        name: "APT-C-23",
        aliases: &[
            "Mantis",
            "Arid Viper",
            "Desert Falcon",
            "TAG-63",
            "Grey Karkadann",
            "Big Bang APT",
            "Two-tailed Scorpion",
        ],
        software: &["Micropsia"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1030",
        name: "Agrius",
        aliases: &[
            "Pink Sandstorm",
            "AMERICIUM",
            "Agonizing Serpens",
            "BlackShadow",
        ],
        software: &[
            "ASPXSpy",
            "Apostle",
            "BFG Agonizer",
            "DEADWOOD",
            "IPsec Helper",
            "Mimikatz",
            "Moneybird",
            "MultiLayer Wiper",
            "NBTscan",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1031",
        name: "Saint Bear",
        aliases: &["Storm-0587", "TA471", "UAC-0056", "Lorec53"],
        software: &["OutSteel", "Saint Bot"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1032",
        name: "INC Ransom",
        aliases: &["GOLD IONIC"],
        software: &[
            "AdFind",
            "INC Ransomware",
            "Net",
            "Nltest",
            "PsExec",
            "Rclone",
            "Tor",
            "esentutl",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1033",
        name: "Star Blizzard",
        aliases: &["SEABORGIUM", "Callisto Group", "TA446", "COLDRIVER"],
        software: &["Spica"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1034",
        name: "Daggerfly",
        aliases: &["Evasive Panda", "BRONZE HIGHLAND"],
        software: &["BITSAdmin", "MacMa", "MgBot", "Nightdoor", "PlugX", "Reg"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1035",
        name: "Winter Vivern",
        aliases: &["TA473", "UAC-0114"],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1036",
        name: "Moonstone Sleet",
        aliases: &["Storm-1789"],
        software: &["Qilin"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1037",
        name: "TA577",
        aliases: &[],
        software: &["Latrodectus", "Pikabot", "QakBot"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1038",
        name: "TA578",
        aliases: &[],
        software: &["Bumblebee", "IcedID", "Latrodectus"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1039",
        name: "RedCurl",
        aliases: &[],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1040",
        name: "Play",
        aliases: &[],
        software: &[
            "AdFind",
            "BloodHound",
            "Cobalt Strike",
            "Empire",
            "Mimikatz",
            "Nltest",
            "Playcrypt",
            "PsExec",
            "Wevtutil",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1041",
        name: "Sea Turtle",
        aliases: &["Teal Kurma", "Marbled Dust", "Cosmic Wolf", "SILICON"],
        software: &["SnappyTCP"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1042",
        name: "RedEcho",
        aliases: &[],
        software: &["ShadowPad"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1043",
        name: "BlackByte",
        aliases: &["Hecamede"],
        software: &[
            "AdFind",
            "Arp",
            "BlackByte 2.0 Ransomware",
            "BlackByte Ransomware",
            "Cobalt Strike",
            "Exbyte",
            "Mimikatz",
            "PsExec",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1044",
        name: "APT42",
        aliases: &[],
        software: &["NICECURL", "TAMECAT"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1045",
        name: "Salt Typhoon",
        aliases: &[],
        software: &["JumbledPath"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1046",
        name: "Storm-1811",
        aliases: &[],
        software: &[
            "BITSAdmin",
            "Black Basta",
            "Cobalt Strike",
            "Impacket",
            "PsExec",
            "QakBot",
            "Quick Assist",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1047",
        name: "Velvet Ant",
        aliases: &[],
        software: &["Impacket", "PlugX"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1048",
        name: "UNC3886",
        aliases: &[],
        software: &[
            "CASTLETAP",
            "MEDUSA",
            "MOPSLED",
            "REPTILE",
            "RIFLESPINE",
            "THINCRUST",
            "VIRTUALPIE",
            "VIRTUALPITA",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1049",
        name: "AppleJeus",
        aliases: &["Gleaming Pisces", "Citrine Sleet", "UNC1720", "UNC4736"],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1050",
        name: "Water Galura",
        aliases: &["GOLD FEATHER"],
        software: &["Qilin", "Tor"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1051",
        name: "Medusa Group",
        aliases: &[],
        software: &[
            "Medusa Ransomware",
            "Mimikatz",
            "PsExec",
            "Rclone",
            "certutil",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1052",
        name: "Contagious Interview",
        aliases: &[
            "DeceptiveDevelopment",
            "Gwisin Gang",
            "Tenacious Pungsan",
            "DEV#POPPER",
            "PurpleBravo",
            "TAG-121",
        ],
        software: &[
            "BeaverTail",
            "HexEval Loader",
            "InvisibleFerret",
            "XORIndex Loader",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1053",
        name: "Storm-0501",
        aliases: &[],
        software: &[
            "AADInternals",
            "Cobalt Strike",
            "Embargo",
            "Impacket",
            "Net",
            "Nltest",
            "Rclone",
            "Tasklist",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1054",
        name: "MirrorFace",
        aliases: &["Earth Kasha"],
        software: &[
            "BITSAdmin",
            "Cobalt Strike",
            "DOWNIISSA",
            "HiddenFace",
            "LODEINFO",
            "MirrorStealer",
            "NOOPLDR",
            "Net",
            "Nltest",
            "Ping",
            "ROAMINGHOUSE",
            "Tasklist",
            "UPPERCUT",
            "Wevtutil",
            "ipconfig",
            "nbtstat",
        ],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1055",
        name: "VOID MANTICORE",
        aliases: &[
            "COBALT MYSTIQUE",
            "Handala Hack",
            "Homeland Justice",
            "Karma",
            "Karmabelow80",
            "BANISHED KITTEN",
            "Red Sandstorm",
        ],
        software: &[],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1056",
        name: "TeamPCP",
        aliases: &[
            "PCPCat",
            "ShellForce",
            "DeadCatx3",
            "SHADOW-WATER-058",
            "UNC6780",
        ],
        software: &["CanisterWorm", "Mini Shai-Hulud", "TeamPCP Cloud Stealer"],
        origin: "",
    },
    AptGroup {
        mitre_id: "G1057",
        name: "ShinyHunters",
        aliases: &["UNC6240", "Bling Libra"],
        software: &["Tor"],
        origin: "",
    },
];

/// Expand a set of selected group indices into the flat term list for CompiledFilter.
pub fn expand_terms(selected: &[bool]) -> Vec<String> {
    let mut terms = Vec::new();
    for (i, sel) in selected.iter().enumerate() {
        if *sel {
            if let Some(g) = APT_GROUPS.get(i) {
                terms.extend(g.terms());
            }
        }
    }
    terms.sort();
    terms.dedup();
    terms
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn groups_have_terms() {
        for g in APT_GROUPS {
            assert!(!g.terms().is_empty(), "{} has no terms", g.name);
        }
    }

    #[test]
    fn search_matches_alias() {
        let apt28 = APT_GROUPS.iter().find(|g| g.name == "APT28").unwrap();
        assert!(apt28.matches_search("fancy bear"));
        assert!(apt28.matches_search("g0007"));
        assert!(!apt28.matches_search("lazarus"));
    }

    #[test]
    fn expand_dedups() {
        let mut sel = vec![false; APT_GROUPS.len()];
        sel[0] = true;
        let terms = expand_terms(&sel);
        assert!(!terms.is_empty());
    }

    #[test]
    fn no_duplicate_mitre_ids() {
        let mut ids: Vec<&str> = APT_GROUPS.iter().map(|g| g.mitre_id).collect();
        let before = ids.len();
        ids.sort();
        ids.dedup();
        assert_eq!(before, ids.len(), "duplicate MITRE group ids in catalog");
    }

    #[test]
    fn covers_full_mitre_group_list() {
        // Sanity floor: MITRE tracks 170+ non-deprecated enterprise groups;
        // guards against an accidental truncation regressing the catalog
        // back to the old hand-picked ~40-entry subset.
        assert!(
            APT_GROUPS.len() > 150,
            "expected the full MITRE group list, got {} entries",
            APT_GROUPS.len()
        );
    }
}
