//! MITRE ATT&CK technique (TTP) catalog for the rules screen.
//!
//! Curated, detection-relevant enterprise techniques grouped by tactic.
//! Selecting entries activates technique filtering (see `filter.rs`);
//! selecting none leaves the filter inactive so every rule is kept.
//! Parent codes also match their subtechniques (T1059 keeps T1059.001).

pub struct TtpDef {
    /// ATT&CK ID, e.g. "T1059" or "T1566.001"
    pub id: &'static str,
    /// technique name as shown in ATT&CK
    pub name: &'static str,
    /// tactic used as the section header
    pub tactic: &'static str,
}

const fn t(id: &'static str, name: &'static str, tactic: &'static str) -> TtpDef {
    TtpDef { id, name, tactic }
}

pub static TTP_CATALOG: &[TtpDef] = &[
    // ---- Initial Access ----
    t("T1566", "Phishing", "Initial Access"),
    t("T1566.001", "Spearphishing Attachment", "Initial Access"),
    t("T1566.002", "Spearphishing Link", "Initial Access"),
    t(
        "T1190",
        "Exploit Public-Facing Application",
        "Initial Access",
    ),
    t("T1133", "External Remote Services", "Initial Access"),
    t("T1078", "Valid Accounts", "Initial Access"),
    t("T1189", "Drive-by Compromise", "Initial Access"),
    t("T1195", "Supply Chain Compromise", "Initial Access"),
    t(
        "T1091",
        "Replication Through Removable Media",
        "Initial Access",
    ),
    // ---- Execution ----
    t("T1059", "Command and Scripting Interpreter", "Execution"),
    t("T1059.001", "PowerShell", "Execution"),
    t("T1059.003", "Windows Command Shell", "Execution"),
    t("T1059.004", "Unix Shell", "Execution"),
    t("T1059.005", "Visual Basic", "Execution"),
    t("T1059.006", "Python", "Execution"),
    t("T1059.007", "JavaScript", "Execution"),
    t("T1047", "Windows Management Instrumentation", "Execution"),
    t("T1053", "Scheduled Task/Job", "Execution"),
    t("T1053.005", "Scheduled Task", "Execution"),
    t("T1204", "User Execution", "Execution"),
    t("T1204.002", "Malicious File", "Execution"),
    t("T1569.002", "Service Execution", "Execution"),
    t("T1203", "Exploitation for Client Execution", "Execution"),
    t("T1129", "Shared Modules", "Execution"),
    // ---- Persistence ----
    t("T1547", "Boot or Logon Autostart Execution", "Persistence"),
    t(
        "T1547.001",
        "Registry Run Keys / Startup Folder",
        "Persistence",
    ),
    t("T1543", "Create or Modify System Process", "Persistence"),
    t("T1543.003", "Windows Service", "Persistence"),
    t("T1136", "Create Account", "Persistence"),
    t("T1136.001", "Local Account", "Persistence"),
    t("T1098", "Account Manipulation", "Persistence"),
    t("T1505.003", "Web Shell", "Persistence"),
    t("T1574", "Hijack Execution Flow", "Persistence"),
    t("T1574.001", "DLL Search Order Hijacking", "Persistence"),
    t("T1574.002", "DLL Side-Loading", "Persistence"),
    t("T1546", "Event Triggered Execution", "Persistence"),
    t("T1546.003", "WMI Event Subscription", "Persistence"),
    t("T1546.008", "Accessibility Features", "Persistence"),
    t(
        "T1546.012",
        "Image File Execution Options Injection",
        "Persistence",
    ),
    t("T1197", "BITS Jobs", "Persistence"),
    t("T1053.003", "Cron", "Persistence"),
    // ---- Privilege Escalation ----
    t(
        "T1548",
        "Abuse Elevation Control Mechanism",
        "Privilege Escalation",
    ),
    t(
        "T1548.002",
        "Bypass User Account Control",
        "Privilege Escalation",
    ),
    t("T1548.003", "Sudo and Sudo Caching", "Privilege Escalation"),
    t("T1055", "Process Injection", "Privilege Escalation"),
    t("T1055.001", "DLL Injection", "Privilege Escalation"),
    t("T1055.012", "Process Hollowing", "Privilege Escalation"),
    t(
        "T1068",
        "Exploitation for Privilege Escalation",
        "Privilege Escalation",
    ),
    t("T1134", "Access Token Manipulation", "Privilege Escalation"),
    t(
        "T1484",
        "Domain or Tenant Policy Modification",
        "Privilege Escalation",
    ),
    // ---- Defense Evasion ----
    t(
        "T1027",
        "Obfuscated Files or Information",
        "Defense Evasion",
    ),
    t("T1027.010", "Command Obfuscation", "Defense Evasion"),
    t(
        "T1140",
        "Deobfuscate/Decode Files or Information",
        "Defense Evasion",
    ),
    t("T1218", "System Binary Proxy Execution", "Defense Evasion"),
    t("T1218.005", "Mshta", "Defense Evasion"),
    t("T1218.010", "Regsvr32", "Defense Evasion"),
    t("T1218.011", "Rundll32", "Defense Evasion"),
    t("T1216", "System Script Proxy Execution", "Defense Evasion"),
    t("T1112", "Modify Registry", "Defense Evasion"),
    t("T1070", "Indicator Removal", "Defense Evasion"),
    t("T1070.001", "Clear Windows Event Logs", "Defense Evasion"),
    t("T1070.004", "File Deletion", "Defense Evasion"),
    t("T1562", "Impair Defenses", "Defense Evasion"),
    t("T1562.001", "Disable or Modify Tools", "Defense Evasion"),
    t(
        "T1562.004",
        "Disable or Modify System Firewall",
        "Defense Evasion",
    ),
    t("T1036", "Masquerading", "Defense Evasion"),
    t(
        "T1036.005",
        "Match Legitimate Name or Location",
        "Defense Evasion",
    ),
    t(
        "T1055.002",
        "Portable Executable Injection",
        "Defense Evasion",
    ),
    t(
        "T1127",
        "Trusted Developer Utilities Proxy Execution",
        "Defense Evasion",
    ),
    t("T1127.001", "MSBuild", "Defense Evasion"),
    t("T1220", "XSL Script Processing", "Defense Evasion"),
    t("T1553", "Subvert Trust Controls", "Defense Evasion"),
    t("T1553.002", "Code Signing", "Defense Evasion"),
    t("T1564", "Hide Artifacts", "Defense Evasion"),
    t(
        "T1564.001",
        "Hidden Files and Directories",
        "Defense Evasion",
    ),
    t("T1564.003", "Hidden Window", "Defense Evasion"),
    t("T1202", "Indirect Command Execution", "Defense Evasion"),
    t("T1497", "Virtualization/Sandbox Evasion", "Defense Evasion"),
    t("T1078.003", "Local Accounts", "Defense Evasion"),
    t(
        "T1550",
        "Use Alternate Authentication Material",
        "Defense Evasion",
    ),
    t("T1550.002", "Pass the Hash", "Defense Evasion"),
    t("T1550.003", "Pass the Ticket", "Defense Evasion"),
    // ---- Credential Access ----
    t("T1003", "OS Credential Dumping", "Credential Access"),
    t("T1003.001", "LSASS Memory", "Credential Access"),
    t("T1003.002", "Security Account Manager", "Credential Access"),
    t("T1003.003", "NTDS", "Credential Access"),
    t("T1003.006", "DCSync", "Credential Access"),
    t("T1110", "Brute Force", "Credential Access"),
    t("T1110.001", "Password Guessing", "Credential Access"),
    t("T1110.003", "Password Spraying", "Credential Access"),
    t(
        "T1555",
        "Credentials from Password Stores",
        "Credential Access",
    ),
    t(
        "T1555.003",
        "Credentials from Web Browsers",
        "Credential Access",
    ),
    t(
        "T1558",
        "Steal or Forge Kerberos Tickets",
        "Credential Access",
    ),
    t("T1558.003", "Kerberoasting", "Credential Access"),
    t("T1558.004", "AS-REP Roasting", "Credential Access"),
    t("T1552", "Unsecured Credentials", "Credential Access"),
    t("T1552.001", "Credentials In Files", "Credential Access"),
    t(
        "T1556",
        "Modify Authentication Process",
        "Credential Access",
    ),
    t(
        "T1621",
        "Multi-Factor Authentication Request Generation",
        "Credential Access",
    ),
    t("T1056.001", "Keylogging", "Credential Access"),
    t("T1539", "Steal Web Session Cookie", "Credential Access"),
    // ---- Discovery ----
    t("T1082", "System Information Discovery", "Discovery"),
    t("T1083", "File and Directory Discovery", "Discovery"),
    t("T1057", "Process Discovery", "Discovery"),
    t("T1018", "Remote System Discovery", "Discovery"),
    t(
        "T1016",
        "System Network Configuration Discovery",
        "Discovery",
    ),
    t("T1049", "System Network Connections Discovery", "Discovery"),
    t("T1033", "System Owner/User Discovery", "Discovery"),
    t("T1087", "Account Discovery", "Discovery"),
    t("T1087.002", "Domain Account", "Discovery"),
    t("T1069", "Permission Groups Discovery", "Discovery"),
    t("T1069.002", "Domain Groups", "Discovery"),
    t("T1482", "Domain Trust Discovery", "Discovery"),
    t("T1046", "Network Service Discovery", "Discovery"),
    t("T1135", "Network Share Discovery", "Discovery"),
    t("T1518.001", "Security Software Discovery", "Discovery"),
    t("T1201", "Password Policy Discovery", "Discovery"),
    t("T1012", "Query Registry", "Discovery"),
    t("T1007", "System Service Discovery", "Discovery"),
    // ---- Lateral Movement ----
    t("T1021", "Remote Services", "Lateral Movement"),
    t("T1021.001", "Remote Desktop Protocol", "Lateral Movement"),
    t("T1021.002", "SMB/Windows Admin Shares", "Lateral Movement"),
    t("T1021.004", "SSH", "Lateral Movement"),
    t("T1021.006", "Windows Remote Management", "Lateral Movement"),
    t("T1570", "Lateral Tool Transfer", "Lateral Movement"),
    t(
        "T1210",
        "Exploitation of Remote Services",
        "Lateral Movement",
    ),
    t("T1080", "Taint Shared Content", "Lateral Movement"),
    // ---- Collection ----
    t("T1560", "Archive Collected Data", "Collection"),
    t("T1560.001", "Archive via Utility", "Collection"),
    t("T1005", "Data from Local System", "Collection"),
    t("T1039", "Data from Network Shared Drive", "Collection"),
    t("T1114", "Email Collection", "Collection"),
    t("T1114.002", "Remote Email Collection", "Collection"),
    t("T1113", "Screen Capture", "Collection"),
    t("T1115", "Clipboard Data", "Collection"),
    t("T1074", "Data Staged", "Collection"),
    // ---- Command and Control ----
    t("T1071", "Application Layer Protocol", "Command and Control"),
    t("T1071.001", "Web Protocols", "Command and Control"),
    t("T1071.004", "DNS", "Command and Control"),
    t("T1105", "Ingress Tool Transfer", "Command and Control"),
    t("T1090", "Proxy", "Command and Control"),
    t("T1090.003", "Multi-hop Proxy", "Command and Control"),
    t("T1572", "Protocol Tunneling", "Command and Control"),
    t("T1573", "Encrypted Channel", "Command and Control"),
    t("T1568", "Dynamic Resolution", "Command and Control"),
    t(
        "T1568.002",
        "Domain Generation Algorithms",
        "Command and Control",
    ),
    t("T1219", "Remote Access Software", "Command and Control"),
    t("T1102", "Web Service", "Command and Control"),
    t("T1132", "Data Encoding", "Command and Control"),
    // ---- Exfiltration ----
    t("T1041", "Exfiltration Over C2 Channel", "Exfiltration"),
    t(
        "T1048",
        "Exfiltration Over Alternative Protocol",
        "Exfiltration",
    ),
    t(
        "T1048.003",
        "Exfil Over Unencrypted Non-C2 Protocol",
        "Exfiltration",
    ),
    t("T1567", "Exfiltration Over Web Service", "Exfiltration"),
    t("T1567.002", "Exfiltration to Cloud Storage", "Exfiltration"),
    t("T1029", "Scheduled Transfer", "Exfiltration"),
    t("T1030", "Data Transfer Size Limits", "Exfiltration"),
    // ---- Impact ----
    t("T1486", "Data Encrypted for Impact", "Impact"),
    t("T1490", "Inhibit System Recovery", "Impact"),
    t("T1489", "Service Stop", "Impact"),
    t("T1485", "Data Destruction", "Impact"),
    t("T1491", "Defacement", "Impact"),
    t("T1531", "Account Access Removal", "Impact"),
    t("T1498", "Network Denial of Service", "Impact"),
    t("T1496", "Resource Hijacking", "Impact"),
    t("T1529", "System Shutdown/Reboot", "Impact"),
];
