//! MITRE ATT&CK technique (TTP) catalog for the rules screen.
//!
//! Full enterprise-attack matrix (techniques + sub-techniques), generated
//! from the official MITRE CTI STIX bundle so every published ATT&CK ID is
//! filterable here. Tactics reflect the current (v17+) taxonomy, which
//! split the old "Defense Evasion" tactic into "Stealth" and "Defense
//! Impairment". Selecting entries activates technique filtering (see
//! `filter.rs`); selecting none leaves the filter inactive so every rule
//! is kept. Parent codes also match their subtechniques (T1059 keeps
//! T1059.001).

pub struct TtpDef {
    /// ATT&CK ID, e.g. "T1059" or "T1566.001"
    pub id: &'static str,
    /// technique name as shown in ATT&CK
    pub name: &'static str,
    /// tactic used as the section header
    pub tactic: &'static str,
}

const fn t(id: &'static str, name: &'static str, tactic: &'static str) -> TtpDef {
    TtpDef { id, name, tactic }
}

pub static TTP_CATALOG: &[TtpDef] = &[
    // ---- Reconnaissance ----
    t(
        "T1589",
        "Gather Victim Identity Information",
        "Reconnaissance",
    ),
    t("T1589.001", "Credentials", "Reconnaissance"),
    t("T1589.002", "Email Addresses", "Reconnaissance"),
    t("T1589.003", "Employee Names", "Reconnaissance"),
    t(
        "T1590",
        "Gather Victim Network Information",
        "Reconnaissance",
    ),
    t("T1590.001", "Domain Properties", "Reconnaissance"),
    t("T1590.002", "DNS", "Reconnaissance"),
    t("T1590.003", "Network Trust Dependencies", "Reconnaissance"),
    t("T1590.004", "Network Topology", "Reconnaissance"),
    t("T1590.005", "IP Addresses", "Reconnaissance"),
    t("T1590.006", "Network Security Appliances", "Reconnaissance"),
    t("T1591", "Gather Victim Org Information", "Reconnaissance"),
    t(
        "T1591.001",
        "Determine Physical Locations",
        "Reconnaissance",
    ),
    t("T1591.002", "Business Relationships", "Reconnaissance"),
    t("T1591.003", "Identify Business Tempo", "Reconnaissance"),
    t("T1591.004", "Identify Roles", "Reconnaissance"),
    t("T1592", "Gather Victim Host Information", "Reconnaissance"),
    t("T1592.001", "Hardware", "Reconnaissance"),
    t("T1592.002", "Software", "Reconnaissance"),
    t("T1592.003", "Firmware", "Reconnaissance"),
    t("T1592.004", "Client Configurations", "Reconnaissance"),
    t("T1593", "Search Open Websites/Domains", "Reconnaissance"),
    t("T1593.001", "Social Media", "Reconnaissance"),
    t("T1593.002", "Search Engines", "Reconnaissance"),
    t("T1593.003", "Code Repositories", "Reconnaissance"),
    t("T1594", "Search Victim-Owned Websites", "Reconnaissance"),
    t("T1595", "Active Scanning", "Reconnaissance"),
    t("T1595.001", "Scanning IP Blocks", "Reconnaissance"),
    t("T1595.002", "Vulnerability Scanning", "Reconnaissance"),
    t("T1595.003", "Wordlist Scanning", "Reconnaissance"),
    t("T1596", "Search Open Technical Databases", "Reconnaissance"),
    t("T1596.001", "DNS/Passive DNS", "Reconnaissance"),
    t("T1596.002", "WHOIS", "Reconnaissance"),
    t("T1596.003", "Digital Certificates", "Reconnaissance"),
    t("T1596.004", "CDNs", "Reconnaissance"),
    t("T1596.005", "Scan Databases", "Reconnaissance"),
    t("T1597", "Search Closed Sources", "Reconnaissance"),
    t("T1597.001", "Threat Intel Vendors", "Reconnaissance"),
    t("T1597.002", "Purchase Technical Data", "Reconnaissance"),
    t("T1598", "Phishing for Information", "Reconnaissance"),
    t("T1598.001", "Spearphishing Service", "Reconnaissance"),
    t("T1598.002", "Spearphishing Attachment", "Reconnaissance"),
    t("T1598.003", "Spearphishing Link", "Reconnaissance"),
    t("T1598.004", "Spearphishing Voice", "Reconnaissance"),
    t("T1681", "Search Threat Vendor Data", "Reconnaissance"),
    t("T1682", "Query Public AI Services", "Reconnaissance"),
    // ---- Resource Development ----
    t("T1583", "Acquire Infrastructure", "Resource Development"),
    t("T1583.001", "Domains", "Resource Development"),
    t("T1583.002", "DNS Server", "Resource Development"),
    t(
        "T1583.003",
        "Virtual Private Server",
        "Resource Development",
    ),
    t("T1583.004", "Server", "Resource Development"),
    t("T1583.005", "Botnet", "Resource Development"),
    t("T1583.006", "Web Services", "Resource Development"),
    t("T1583.007", "Serverless", "Resource Development"),
    t("T1583.008", "Malvertising", "Resource Development"),
    t("T1584", "Compromise Infrastructure", "Resource Development"),
    t("T1584.001", "Domains", "Resource Development"),
    t("T1584.002", "DNS Server", "Resource Development"),
    t(
        "T1584.003",
        "Virtual Private Server",
        "Resource Development",
    ),
    t("T1584.004", "Server", "Resource Development"),
    t("T1584.005", "Botnet", "Resource Development"),
    t("T1584.006", "Web Services", "Resource Development"),
    t("T1584.007", "Serverless", "Resource Development"),
    t("T1584.008", "Network Devices", "Resource Development"),
    t("T1585", "Establish Accounts", "Resource Development"),
    t("T1585.001", "Social Media Accounts", "Resource Development"),
    t("T1585.002", "Email Accounts", "Resource Development"),
    t("T1585.003", "Cloud Accounts", "Resource Development"),
    t("T1586", "Compromise Accounts", "Resource Development"),
    t("T1586.001", "Social Media Accounts", "Resource Development"),
    t("T1586.002", "Email Accounts", "Resource Development"),
    t("T1586.003", "Cloud Accounts", "Resource Development"),
    t("T1587", "Develop Capabilities", "Resource Development"),
    t("T1587.001", "Malware", "Resource Development"),
    t(
        "T1587.002",
        "Code Signing Certificates",
        "Resource Development",
    ),
    t("T1587.003", "Digital Certificates", "Resource Development"),
    t("T1587.004", "Exploits", "Resource Development"),
    t("T1588", "Obtain Capabilities", "Resource Development"),
    t("T1588.001", "Malware", "Resource Development"),
    t("T1588.002", "Tool", "Resource Development"),
    t(
        "T1588.003",
        "Code Signing Certificates",
        "Resource Development",
    ),
    t("T1588.004", "Digital Certificates", "Resource Development"),
    t("T1588.005", "Exploits", "Resource Development"),
    t("T1588.006", "Vulnerabilities", "Resource Development"),
    t(
        "T1588.007",
        "Artificial Intelligence",
        "Resource Development",
    ),
    t("T1608", "Stage Capabilities", "Resource Development"),
    t("T1608.001", "Upload Malware", "Resource Development"),
    t("T1608.002", "Upload Tool", "Resource Development"),
    t(
        "T1608.003",
        "Install Digital Certificate",
        "Resource Development",
    ),
    t("T1608.004", "Drive-by Target", "Resource Development"),
    t("T1608.005", "Link Target", "Resource Development"),
    t("T1608.006", "SEO Poisoning", "Resource Development"),
    t("T1650", "Acquire Access", "Resource Development"),
    t("T1683", "Generate Content", "Resource Development"),
    t("T1683.001", "Written Content", "Resource Development"),
    t("T1683.002", "Audio-Visual Content", "Resource Development"),
    // ---- Initial Access ----
    t("T1078", "Valid Accounts", "Initial Access"),
    t("T1078.001", "Default Accounts", "Initial Access"),
    t("T1078.002", "Domain Accounts", "Initial Access"),
    t("T1078.003", "Local Accounts", "Initial Access"),
    t("T1078.004", "Cloud Accounts", "Initial Access"),
    t(
        "T1091",
        "Replication Through Removable Media",
        "Initial Access",
    ),
    t("T1133", "External Remote Services", "Initial Access"),
    t("T1189", "Drive-by Compromise", "Initial Access"),
    t(
        "T1190",
        "Exploit Public-Facing Application",
        "Initial Access",
    ),
    t("T1195", "Supply Chain Compromise", "Initial Access"),
    t(
        "T1195.001",
        "Compromise Software Dependencies and Development Tools",
        "Initial Access",
    ),
    t(
        "T1195.002",
        "Compromise Software Supply Chain",
        "Initial Access",
    ),
    t(
        "T1195.003",
        "Compromise Hardware Supply Chain",
        "Initial Access",
    ),
    t("T1199", "Trusted Relationship", "Initial Access"),
    t("T1200", "Hardware Additions", "Initial Access"),
    t("T1566", "Phishing", "Initial Access"),
    t("T1566.001", "Spearphishing Attachment", "Initial Access"),
    t("T1566.002", "Spearphishing Link", "Initial Access"),
    t("T1566.003", "Spearphishing via Service", "Initial Access"),
    t("T1566.004", "Spearphishing Voice", "Initial Access"),
    t("T1659", "Content Injection", "Initial Access"),
    t("T1669", "Wi-Fi Networks", "Initial Access"),
    // ---- Execution ----
    t("T1047", "Windows Management Instrumentation", "Execution"),
    t("T1053", "Scheduled Task/Job", "Execution"),
    t("T1053.002", "At", "Execution"),
    t("T1053.003", "Cron", "Execution"),
    t("T1053.005", "Scheduled Task", "Execution"),
    t("T1053.006", "Systemd Timers", "Execution"),
    t("T1053.007", "Container Orchestration Job", "Execution"),
    t("T1059", "Command and Scripting Interpreter", "Execution"),
    t("T1059.001", "PowerShell", "Execution"),
    t("T1059.002", "AppleScript", "Execution"),
    t("T1059.003", "Windows Command Shell", "Execution"),
    t("T1059.004", "Unix Shell", "Execution"),
    t("T1059.005", "Visual Basic", "Execution"),
    t("T1059.006", "Python", "Execution"),
    t("T1059.007", "JavaScript", "Execution"),
    t("T1059.008", "Network Device CLI", "Execution"),
    t("T1059.009", "Cloud API", "Execution"),
    t("T1059.010", "AutoHotKey & AutoIT", "Execution"),
    t("T1059.011", "Lua", "Execution"),
    t("T1059.012", "Hypervisor CLI", "Execution"),
    t("T1059.013", "Container CLI/API", "Execution"),
    t("T1072", "Software Deployment Tools", "Execution"),
    t("T1106", "Native API", "Execution"),
    t(
        "T1127",
        "Trusted Developer Utilities Proxy Execution",
        "Execution",
    ),
    t("T1127.001", "MSBuild", "Execution"),
    t("T1127.002", "ClickOnce", "Execution"),
    t("T1127.003", "JamPlus", "Execution"),
    t("T1129", "Shared Modules", "Execution"),
    t("T1197", "BITS Jobs", "Execution"),
    t("T1203", "Exploitation for Client Execution", "Execution"),
    t("T1204", "User Execution", "Execution"),
    t("T1204.001", "Malicious Link", "Execution"),
    t("T1204.002", "Malicious File", "Execution"),
    t("T1204.003", "Malicious Image", "Execution"),
    t("T1204.004", "Malicious Copy and Paste", "Execution"),
    t("T1204.005", "Malicious Library", "Execution"),
    t("T1559", "Inter-Process Communication", "Execution"),
    t("T1559.001", "Component Object Model", "Execution"),
    t("T1559.002", "Dynamic Data Exchange", "Execution"),
    t("T1559.003", "XPC Services", "Execution"),
    t("T1569", "System Services", "Execution"),
    t("T1569.001", "Launchctl", "Execution"),
    t("T1569.002", "Service Execution", "Execution"),
    t("T1569.003", "Systemctl", "Execution"),
    t("T1574", "Hijack Execution Flow", "Execution"),
    t("T1574.001", "DLL", "Execution"),
    t("T1574.004", "Dylib Hijacking", "Execution"),
    t(
        "T1574.005",
        "Executable Installer File Permissions Weakness",
        "Execution",
    ),
    t("T1574.006", "Dynamic Linker Hijacking", "Execution"),
    t(
        "T1574.007",
        "Path Interception by PATH Environment Variable",
        "Execution",
    ),
    t(
        "T1574.008",
        "Path Interception by Search Order Hijacking",
        "Execution",
    ),
    t(
        "T1574.009",
        "Path Interception by Unquoted Path",
        "Execution",
    ),
    t(
        "T1574.010",
        "Services File Permissions Weakness",
        "Execution",
    ),
    t(
        "T1574.011",
        "Services Registry Permissions Weakness",
        "Execution",
    ),
    t("T1574.012", "COR_PROFILER", "Execution"),
    t("T1574.013", "KernelCallbackTable", "Execution"),
    t("T1574.014", "AppDomainManager", "Execution"),
    t("T1609", "Container Administration Command", "Execution"),
    t("T1610", "Deploy Container", "Execution"),
    t("T1648", "Serverless Execution", "Execution"),
    t("T1651", "Cloud Administration Command", "Execution"),
    t("T1674", "Input Injection", "Execution"),
    t("T1675", "ESXi Administration Command", "Execution"),
    t("T1677", "Poisoned Pipeline Execution", "Execution"),
    // ---- Persistence ----
    t(
        "T1037",
        "Boot or Logon Initialization Scripts",
        "Persistence",
    ),
    t("T1037.001", "Logon Script (Windows)", "Persistence"),
    t("T1037.002", "Login Hook", "Persistence"),
    t("T1037.003", "Network Logon Script", "Persistence"),
    t("T1037.004", "RC Scripts", "Persistence"),
    t("T1037.005", "Startup Items", "Persistence"),
    t("T1053", "Scheduled Task/Job", "Persistence"),
    t("T1053.002", "At", "Persistence"),
    t("T1053.003", "Cron", "Persistence"),
    t("T1053.005", "Scheduled Task", "Persistence"),
    t("T1053.006", "Systemd Timers", "Persistence"),
    t("T1053.007", "Container Orchestration Job", "Persistence"),
    t("T1078", "Valid Accounts", "Persistence"),
    t("T1078.001", "Default Accounts", "Persistence"),
    t("T1078.002", "Domain Accounts", "Persistence"),
    t("T1078.003", "Local Accounts", "Persistence"),
    t("T1078.004", "Cloud Accounts", "Persistence"),
    t("T1098", "Account Manipulation", "Persistence"),
    t("T1098.001", "Additional Cloud Credentials", "Persistence"),
    t(
        "T1098.002",
        "Additional Email Delegate Permissions",
        "Persistence",
    ),
    t("T1098.003", "Additional Cloud Roles", "Persistence"),
    t("T1098.004", "SSH Authorized Keys", "Persistence"),
    t("T1098.005", "Device Registration", "Persistence"),
    t(
        "T1098.006",
        "Additional Container Cluster Roles",
        "Persistence",
    ),
    t(
        "T1098.007",
        "Additional Local or Domain Groups",
        "Persistence",
    ),
    t("T1112", "Modify Registry", "Persistence"),
    t("T1133", "External Remote Services", "Persistence"),
    t("T1136", "Create Account", "Persistence"),
    t("T1136.001", "Local Account", "Persistence"),
    t("T1136.002", "Domain Account", "Persistence"),
    t("T1136.003", "Cloud Account", "Persistence"),
    t("T1137", "Office Application Startup", "Persistence"),
    t("T1137.001", "Office Template Macros", "Persistence"),
    t("T1137.002", "Office Test", "Persistence"),
    t("T1137.003", "Outlook Forms", "Persistence"),
    t("T1137.004", "Outlook Home Page", "Persistence"),
    t("T1137.005", "Outlook Rules", "Persistence"),
    t("T1137.006", "Add-ins", "Persistence"),
    t("T1176", "Software Extensions", "Persistence"),
    t("T1176.001", "Browser Extensions", "Persistence"),
    t("T1176.002", "IDE Extensions", "Persistence"),
    t("T1197", "BITS Jobs", "Persistence"),
    t("T1205", "Traffic Signaling", "Persistence"),
    t("T1205.001", "Port Knocking", "Persistence"),
    t("T1205.002", "Socket Filters", "Persistence"),
    t("T1505", "Server Software Component", "Persistence"),
    t("T1505.001", "SQL Stored Procedures", "Persistence"),
    t("T1505.002", "Transport Agent", "Persistence"),
    t("T1505.003", "Web Shell", "Persistence"),
    t("T1505.004", "IIS Components", "Persistence"),
    t("T1505.005", "Terminal Services DLL", "Persistence"),
    t("T1505.006", "vSphere Installation Bundles", "Persistence"),
    t("T1525", "Implant Internal Image", "Persistence"),
    t("T1542", "Pre-OS Boot", "Persistence"),
    t("T1542.001", "System Firmware", "Persistence"),
    t("T1542.002", "Component Firmware", "Persistence"),
    t("T1542.003", "Bootkit", "Persistence"),
    t("T1542.004", "ROMMONkit", "Persistence"),
    t("T1542.005", "TFTP Boot", "Persistence"),
    t("T1543", "Create or Modify System Process", "Persistence"),
    t("T1543.001", "Launch Agent", "Persistence"),
    t("T1543.002", "Systemd Service", "Persistence"),
    t("T1543.003", "Windows Service", "Persistence"),
    t("T1543.004", "Launch Daemon", "Persistence"),
    t("T1543.005", "Container Service", "Persistence"),
    t("T1546", "Event Triggered Execution", "Persistence"),
    t(
        "T1546.001",
        "Change Default File Association",
        "Persistence",
    ),
    t("T1546.002", "Screensaver", "Persistence"),
    t(
        "T1546.003",
        "Windows Management Instrumentation Event Subscription",
        "Persistence",
    ),
    t(
        "T1546.004",
        "Unix Shell Configuration Modification",
        "Persistence",
    ),
    t("T1546.005", "Trap", "Persistence"),
    t("T1546.006", "LC_LOAD_DYLIB Addition", "Persistence"),
    t("T1546.007", "Netsh Helper DLL", "Persistence"),
    t("T1546.008", "Accessibility Features", "Persistence"),
    t("T1546.009", "AppCert DLLs", "Persistence"),
    t("T1546.010", "AppInit DLLs", "Persistence"),
    t("T1546.011", "Application Shimming", "Persistence"),
    t(
        "T1546.012",
        "Image File Execution Options Injection",
        "Persistence",
    ),
    t("T1546.013", "PowerShell Profile", "Persistence"),
    t("T1546.014", "Emond", "Persistence"),
    t(
        "T1546.015",
        "Component Object Model Hijacking",
        "Persistence",
    ),
    t("T1546.016", "Installer Packages", "Persistence"),
    t("T1546.017", "Udev Rules", "Persistence"),
    t("T1546.018", "Python Startup Hooks", "Persistence"),
    t("T1547", "Boot or Logon Autostart Execution", "Persistence"),
    t(
        "T1547.001",
        "Registry Run Keys / Startup Folder",
        "Persistence",
    ),
    t("T1547.002", "Authentication Package", "Persistence"),
    t("T1547.003", "Time Providers", "Persistence"),
    t("T1547.004", "Winlogon Helper DLL", "Persistence"),
    t("T1547.005", "Security Support Provider", "Persistence"),
    t("T1547.006", "Kernel Modules and Extensions", "Persistence"),
    t("T1547.007", "Re-opened Applications", "Persistence"),
    t("T1547.008", "LSASS Driver", "Persistence"),
    t("T1547.009", "Shortcut Modification", "Persistence"),
    t("T1547.010", "Port Monitors", "Persistence"),
    t("T1547.012", "Print Processors", "Persistence"),
    t("T1547.013", "XDG Autostart Entries", "Persistence"),
    t("T1547.014", "Active Setup", "Persistence"),
    t("T1547.015", "Login Items", "Persistence"),
    t("T1554", "Compromise Host Software Binary", "Persistence"),
    t("T1556", "Modify Authentication Process", "Persistence"),
    t(
        "T1556.001",
        "Domain Controller Authentication",
        "Persistence",
    ),
    t("T1556.002", "Password Filter DLL", "Persistence"),
    t(
        "T1556.003",
        "Pluggable Authentication Modules",
        "Persistence",
    ),
    t("T1556.004", "Network Device Authentication", "Persistence"),
    t("T1556.005", "Reversible Encryption", "Persistence"),
    t("T1556.006", "Multi-Factor Authentication", "Persistence"),
    t("T1556.007", "Hybrid Identity", "Persistence"),
    t("T1556.008", "Network Provider DLL", "Persistence"),
    t("T1556.009", "Conditional Access Policies", "Persistence"),
    t("T1653", "Power Settings", "Persistence"),
    t("T1668", "Exclusive Control", "Persistence"),
    t("T1671", "Cloud Application Integration", "Persistence"),
    // ---- Privilege Escalation ----
    t(
        "T1037",
        "Boot or Logon Initialization Scripts",
        "Privilege Escalation",
    ),
    t(
        "T1037.001",
        "Logon Script (Windows)",
        "Privilege Escalation",
    ),
    t("T1037.002", "Login Hook", "Privilege Escalation"),
    t("T1037.003", "Network Logon Script", "Privilege Escalation"),
    t("T1037.004", "RC Scripts", "Privilege Escalation"),
    t("T1037.005", "Startup Items", "Privilege Escalation"),
    t("T1053", "Scheduled Task/Job", "Privilege Escalation"),
    t("T1053.002", "At", "Privilege Escalation"),
    t("T1053.003", "Cron", "Privilege Escalation"),
    t("T1053.005", "Scheduled Task", "Privilege Escalation"),
    t("T1053.006", "Systemd Timers", "Privilege Escalation"),
    t(
        "T1053.007",
        "Container Orchestration Job",
        "Privilege Escalation",
    ),
    t("T1055", "Process Injection", "Privilege Escalation"),
    t(
        "T1055.001",
        "Dynamic-link Library Injection",
        "Privilege Escalation",
    ),
    t(
        "T1055.002",
        "Portable Executable Injection",
        "Privilege Escalation",
    ),
    t(
        "T1055.003",
        "Thread Execution Hijacking",
        "Privilege Escalation",
    ),
    t(
        "T1055.004",
        "Asynchronous Procedure Call",
        "Privilege Escalation",
    ),
    t("T1055.005", "Thread Local Storage", "Privilege Escalation"),
    t("T1055.008", "Ptrace System Calls", "Privilege Escalation"),
    t("T1055.009", "Proc Memory", "Privilege Escalation"),
    t(
        "T1055.011",
        "Extra Window Memory Injection",
        "Privilege Escalation",
    ),
    t("T1055.012", "Process Hollowing", "Privilege Escalation"),
    t("T1055.013", "Process Doppelgänging", "Privilege Escalation"),
    t("T1055.014", "VDSO Hijacking", "Privilege Escalation"),
    t("T1055.015", "ListPlanting", "Privilege Escalation"),
    t(
        "T1068",
        "Exploitation for Privilege Escalation",
        "Privilege Escalation",
    ),
    t("T1078", "Valid Accounts", "Privilege Escalation"),
    t("T1078.001", "Default Accounts", "Privilege Escalation"),
    t("T1078.002", "Domain Accounts", "Privilege Escalation"),
    t("T1078.003", "Local Accounts", "Privilege Escalation"),
    t("T1078.004", "Cloud Accounts", "Privilege Escalation"),
    t("T1098", "Account Manipulation", "Privilege Escalation"),
    t(
        "T1098.001",
        "Additional Cloud Credentials",
        "Privilege Escalation",
    ),
    t(
        "T1098.002",
        "Additional Email Delegate Permissions",
        "Privilege Escalation",
    ),
    t(
        "T1098.003",
        "Additional Cloud Roles",
        "Privilege Escalation",
    ),
    t("T1098.004", "SSH Authorized Keys", "Privilege Escalation"),
    t("T1098.005", "Device Registration", "Privilege Escalation"),
    t(
        "T1098.006",
        "Additional Container Cluster Roles",
        "Privilege Escalation",
    ),
    t(
        "T1098.007",
        "Additional Local or Domain Groups",
        "Privilege Escalation",
    ),
    t("T1134", "Access Token Manipulation", "Privilege Escalation"),
    t(
        "T1134.001",
        "Token Impersonation/Theft",
        "Privilege Escalation",
    ),
    t(
        "T1134.002",
        "Create Process with Token",
        "Privilege Escalation",
    ),
    t(
        "T1134.003",
        "Make and Impersonate Token",
        "Privilege Escalation",
    ),
    t("T1134.004", "Parent PID Spoofing", "Privilege Escalation"),
    t("T1134.005", "SID-History Injection", "Privilege Escalation"),
    t(
        "T1484",
        "Domain or Tenant Policy Modification",
        "Privilege Escalation",
    ),
    t(
        "T1484.001",
        "Group Policy Modification",
        "Privilege Escalation",
    ),
    t("T1484.002", "Trust Modification", "Privilege Escalation"),
    t(
        "T1543",
        "Create or Modify System Process",
        "Privilege Escalation",
    ),
    t("T1543.001", "Launch Agent", "Privilege Escalation"),
    t("T1543.002", "Systemd Service", "Privilege Escalation"),
    t("T1543.003", "Windows Service", "Privilege Escalation"),
    t("T1543.004", "Launch Daemon", "Privilege Escalation"),
    t("T1543.005", "Container Service", "Privilege Escalation"),
    t("T1546", "Event Triggered Execution", "Privilege Escalation"),
    t(
        "T1546.001",
        "Change Default File Association",
        "Privilege Escalation",
    ),
    t("T1546.002", "Screensaver", "Privilege Escalation"),
    t(
        "T1546.003",
        "Windows Management Instrumentation Event Subscription",
        "Privilege Escalation",
    ),
    t(
        "T1546.004",
        "Unix Shell Configuration Modification",
        "Privilege Escalation",
    ),
    t("T1546.005", "Trap", "Privilege Escalation"),
    t(
        "T1546.006",
        "LC_LOAD_DYLIB Addition",
        "Privilege Escalation",
    ),
    t("T1546.007", "Netsh Helper DLL", "Privilege Escalation"),
    t(
        "T1546.008",
        "Accessibility Features",
        "Privilege Escalation",
    ),
    t("T1546.009", "AppCert DLLs", "Privilege Escalation"),
    t("T1546.010", "AppInit DLLs", "Privilege Escalation"),
    t("T1546.011", "Application Shimming", "Privilege Escalation"),
    t(
        "T1546.012",
        "Image File Execution Options Injection",
        "Privilege Escalation",
    ),
    t("T1546.013", "PowerShell Profile", "Privilege Escalation"),
    t("T1546.014", "Emond", "Privilege Escalation"),
    t(
        "T1546.015",
        "Component Object Model Hijacking",
        "Privilege Escalation",
    ),
    t("T1546.016", "Installer Packages", "Privilege Escalation"),
    t("T1546.017", "Udev Rules", "Privilege Escalation"),
    t("T1546.018", "Python Startup Hooks", "Privilege Escalation"),
    t(
        "T1547",
        "Boot or Logon Autostart Execution",
        "Privilege Escalation",
    ),
    t(
        "T1547.001",
        "Registry Run Keys / Startup Folder",
        "Privilege Escalation",
    ),
    t(
        "T1547.002",
        "Authentication Package",
        "Privilege Escalation",
    ),
    t("T1547.003", "Time Providers", "Privilege Escalation"),
    t("T1547.004", "Winlogon Helper DLL", "Privilege Escalation"),
    t(
        "T1547.005",
        "Security Support Provider",
        "Privilege Escalation",
    ),
    t(
        "T1547.006",
        "Kernel Modules and Extensions",
        "Privilege Escalation",
    ),
    t(
        "T1547.007",
        "Re-opened Applications",
        "Privilege Escalation",
    ),
    t("T1547.008", "LSASS Driver", "Privilege Escalation"),
    t("T1547.009", "Shortcut Modification", "Privilege Escalation"),
    t("T1547.010", "Port Monitors", "Privilege Escalation"),
    t("T1547.012", "Print Processors", "Privilege Escalation"),
    t("T1547.013", "XDG Autostart Entries", "Privilege Escalation"),
    t("T1547.014", "Active Setup", "Privilege Escalation"),
    t("T1547.015", "Login Items", "Privilege Escalation"),
    t(
        "T1548",
        "Abuse Elevation Control Mechanism",
        "Privilege Escalation",
    ),
    t("T1548.001", "Setuid and Setgid", "Privilege Escalation"),
    t(
        "T1548.002",
        "Bypass User Account Control",
        "Privilege Escalation",
    ),
    t("T1548.003", "Sudo and Sudo Caching", "Privilege Escalation"),
    t(
        "T1548.004",
        "Elevated Execution with Prompt",
        "Privilege Escalation",
    ),
    t(
        "T1548.005",
        "Temporary Elevated Cloud Access",
        "Privilege Escalation",
    ),
    t("T1548.006", "TCC Manipulation", "Privilege Escalation"),
    t("T1611", "Escape to Host", "Privilege Escalation"),
    // ---- Stealth ----
    t("T1006", "Direct Volume Access", "Stealth"),
    t("T1014", "Rootkit", "Stealth"),
    t("T1027", "Obfuscated Files or Information", "Stealth"),
    t("T1027.001", "Binary Padding", "Stealth"),
    t("T1027.002", "Software Packing", "Stealth"),
    t("T1027.003", "Steganography", "Stealth"),
    t("T1027.004", "Compile After Delivery", "Stealth"),
    t("T1027.005", "Indicator Removal from Tools", "Stealth"),
    t("T1027.006", "HTML Smuggling", "Stealth"),
    t("T1027.007", "Dynamic API Resolution", "Stealth"),
    t("T1027.008", "Stripped Payloads", "Stealth"),
    t("T1027.009", "Embedded Payloads", "Stealth"),
    t("T1027.010", "Command Obfuscation", "Stealth"),
    t("T1027.011", "Fileless Storage", "Stealth"),
    t("T1027.012", "LNK Icon Smuggling", "Stealth"),
    t("T1027.013", "Encrypted/Encoded File", "Stealth"),
    t("T1027.014", "Polymorphic Code", "Stealth"),
    t("T1027.015", "Compression", "Stealth"),
    t("T1027.016", "Junk Code Insertion", "Stealth"),
    t("T1027.017", "SVG Smuggling", "Stealth"),
    t("T1027.018", "Invisible Unicode", "Stealth"),
    t("T1036", "Masquerading", "Stealth"),
    t("T1036.001", "Invalid Code Signature", "Stealth"),
    t("T1036.002", "Right-to-Left Override", "Stealth"),
    t("T1036.003", "Rename Legitimate Utilities", "Stealth"),
    t("T1036.004", "Masquerade Task or Service", "Stealth"),
    t(
        "T1036.005",
        "Match Legitimate Resource Name or Location",
        "Stealth",
    ),
    t("T1036.006", "Space after Filename", "Stealth"),
    t("T1036.007", "Double File Extension", "Stealth"),
    t("T1036.008", "Masquerade File Type", "Stealth"),
    t("T1036.009", "Break Process Trees", "Stealth"),
    t("T1036.010", "Masquerade Account Name", "Stealth"),
    t("T1036.011", "Overwrite Process Arguments", "Stealth"),
    t("T1036.012", "Browser Fingerprint", "Stealth"),
    t("T1055", "Process Injection", "Stealth"),
    t("T1055.001", "Dynamic-link Library Injection", "Stealth"),
    t("T1055.002", "Portable Executable Injection", "Stealth"),
    t("T1055.003", "Thread Execution Hijacking", "Stealth"),
    t("T1055.004", "Asynchronous Procedure Call", "Stealth"),
    t("T1055.005", "Thread Local Storage", "Stealth"),
    t("T1055.008", "Ptrace System Calls", "Stealth"),
    t("T1055.009", "Proc Memory", "Stealth"),
    t("T1055.011", "Extra Window Memory Injection", "Stealth"),
    t("T1055.012", "Process Hollowing", "Stealth"),
    t("T1055.013", "Process Doppelgänging", "Stealth"),
    t("T1055.014", "VDSO Hijacking", "Stealth"),
    t("T1055.015", "ListPlanting", "Stealth"),
    t("T1070", "Indicator Removal", "Stealth"),
    t("T1070.003", "Clear Command History", "Stealth"),
    t("T1070.004", "File Deletion", "Stealth"),
    t("T1070.005", "Network Share Connection Removal", "Stealth"),
    t("T1070.006", "Timestomp", "Stealth"),
    t(
        "T1070.007",
        "Clear Network Connection History and Configurations",
        "Stealth",
    ),
    t("T1070.008", "Clear Mailbox Data", "Stealth"),
    t("T1070.009", "Clear Persistence", "Stealth"),
    t("T1070.010", "Relocate Malware", "Stealth"),
    t("T1078", "Valid Accounts", "Stealth"),
    t("T1078.001", "Default Accounts", "Stealth"),
    t("T1078.002", "Domain Accounts", "Stealth"),
    t("T1078.003", "Local Accounts", "Stealth"),
    t("T1078.004", "Cloud Accounts", "Stealth"),
    t(
        "T1127",
        "Trusted Developer Utilities Proxy Execution",
        "Stealth",
    ),
    t("T1127.001", "MSBuild", "Stealth"),
    t("T1127.002", "ClickOnce", "Stealth"),
    t("T1127.003", "JamPlus", "Stealth"),
    t("T1134", "Access Token Manipulation", "Stealth"),
    t("T1134.001", "Token Impersonation/Theft", "Stealth"),
    t("T1134.002", "Create Process with Token", "Stealth"),
    t("T1134.003", "Make and Impersonate Token", "Stealth"),
    t("T1134.004", "Parent PID Spoofing", "Stealth"),
    t("T1134.005", "SID-History Injection", "Stealth"),
    t(
        "T1140",
        "Deobfuscate/Decode Files or Information",
        "Stealth",
    ),
    t("T1197", "BITS Jobs", "Stealth"),
    t("T1202", "Indirect Command Execution", "Stealth"),
    t("T1205", "Traffic Signaling", "Stealth"),
    t("T1205.001", "Port Knocking", "Stealth"),
    t("T1205.002", "Socket Filters", "Stealth"),
    t("T1211", "Exploitation for Stealth", "Stealth"),
    t("T1216", "System Script Proxy Execution", "Stealth"),
    t("T1216.001", "PubPrn", "Stealth"),
    t("T1216.002", "SyncAppvPublishingServer", "Stealth"),
    t("T1218", "System Binary Proxy Execution", "Stealth"),
    t("T1218.001", "Compiled HTML File", "Stealth"),
    t("T1218.002", "Control Panel", "Stealth"),
    t("T1218.003", "CMSTP", "Stealth"),
    t("T1218.004", "InstallUtil", "Stealth"),
    t("T1218.005", "Mshta", "Stealth"),
    t("T1218.007", "Msiexec", "Stealth"),
    t("T1218.008", "Odbcconf", "Stealth"),
    t("T1218.009", "Regsvcs/Regasm", "Stealth"),
    t("T1218.010", "Regsvr32", "Stealth"),
    t("T1218.011", "Rundll32", "Stealth"),
    t("T1218.012", "Verclsid", "Stealth"),
    t("T1218.013", "Mavinject", "Stealth"),
    t("T1218.014", "MMC", "Stealth"),
    t("T1218.015", "Electron Applications", "Stealth"),
    t("T1220", "XSL Script Processing", "Stealth"),
    t("T1221", "Template Injection", "Stealth"),
    t("T1480", "Execution Guardrails", "Stealth"),
    t("T1480.001", "Environmental Keying", "Stealth"),
    t("T1480.002", "Mutual Exclusion", "Stealth"),
    t("T1497", "Virtualization/Sandbox Evasion", "Stealth"),
    t("T1497.001", "System Checks", "Stealth"),
    t("T1497.002", "User Activity Based Checks", "Stealth"),
    t("T1497.003", "Time Based Checks", "Stealth"),
    t("T1535", "Unused/Unsupported Cloud Regions", "Stealth"),
    t("T1542", "Pre-OS Boot", "Stealth"),
    t("T1542.001", "System Firmware", "Stealth"),
    t("T1542.002", "Component Firmware", "Stealth"),
    t("T1542.003", "Bootkit", "Stealth"),
    t("T1542.004", "ROMMONkit", "Stealth"),
    t("T1542.005", "TFTP Boot", "Stealth"),
    t("T1564", "Hide Artifacts", "Stealth"),
    t("T1564.001", "Hidden Files and Directories", "Stealth"),
    t("T1564.002", "Hidden Users", "Stealth"),
    t("T1564.003", "Hidden Window", "Stealth"),
    t("T1564.004", "NTFS File Attributes", "Stealth"),
    t("T1564.005", "Hidden File System", "Stealth"),
    t("T1564.006", "Run Virtual Instance", "Stealth"),
    t("T1564.007", "VBA Stomping", "Stealth"),
    t("T1564.008", "Email Hiding Rules", "Stealth"),
    t("T1564.009", "Resource Forking", "Stealth"),
    t("T1564.010", "Process Argument Spoofing", "Stealth"),
    t("T1564.011", "Ignore Process Interrupts", "Stealth"),
    t("T1564.012", "File/Path Exclusions", "Stealth"),
    t("T1564.013", "Bind Mounts", "Stealth"),
    t("T1564.014", "Extended Attributes", "Stealth"),
    t("T1574", "Hijack Execution Flow", "Stealth"),
    t("T1574.001", "DLL", "Stealth"),
    t("T1574.004", "Dylib Hijacking", "Stealth"),
    t(
        "T1574.005",
        "Executable Installer File Permissions Weakness",
        "Stealth",
    ),
    t("T1574.006", "Dynamic Linker Hijacking", "Stealth"),
    t(
        "T1574.007",
        "Path Interception by PATH Environment Variable",
        "Stealth",
    ),
    t(
        "T1574.008",
        "Path Interception by Search Order Hijacking",
        "Stealth",
    ),
    t("T1574.009", "Path Interception by Unquoted Path", "Stealth"),
    t("T1574.010", "Services File Permissions Weakness", "Stealth"),
    t(
        "T1574.011",
        "Services Registry Permissions Weakness",
        "Stealth",
    ),
    t("T1574.012", "COR_PROFILER", "Stealth"),
    t("T1574.013", "KernelCallbackTable", "Stealth"),
    t("T1574.014", "AppDomainManager", "Stealth"),
    t("T1612", "Build Image on Host", "Stealth"),
    t("T1620", "Reflective Code Loading", "Stealth"),
    t("T1622", "Debugger Evasion", "Stealth"),
    t("T1678", "Delay Execution", "Stealth"),
    t("T1679", "Selective Exclusion", "Stealth"),
    t("T1684", "Social Engineering", "Stealth"),
    t("T1684.001", "Impersonation", "Stealth"),
    t("T1684.002", "Email Spoofing", "Stealth"),
    // ---- Defense Impairment ----
    t("T1112", "Modify Registry", "Defense Impairment"),
    t("T1207", "Rogue Domain Controller", "Defense Impairment"),
    t(
        "T1222",
        "File and Directory Permissions Modification",
        "Defense Impairment",
    ),
    t("T1222.001", "Windows Permissions", "Defense Impairment"),
    t(
        "T1222.002",
        "Linux and Mac Permissions",
        "Defense Impairment",
    ),
    t(
        "T1484",
        "Domain or Tenant Policy Modification",
        "Defense Impairment",
    ),
    t(
        "T1484.001",
        "Group Policy Modification",
        "Defense Impairment",
    ),
    t("T1484.002", "Trust Modification", "Defense Impairment"),
    t("T1553", "Subvert Trust Controls", "Defense Impairment"),
    t("T1553.001", "Gatekeeper Bypass", "Defense Impairment"),
    t("T1553.002", "Code Signing", "Defense Impairment"),
    t(
        "T1553.003",
        "SIP and Trust Provider Hijacking",
        "Defense Impairment",
    ),
    t(
        "T1553.004",
        "Install Root Certificate",
        "Defense Impairment",
    ),
    t("T1553.005", "Mark-of-the-Web Bypass", "Defense Impairment"),
    t(
        "T1553.006",
        "Code Signing Policy Modification",
        "Defense Impairment",
    ),
    t(
        "T1556",
        "Modify Authentication Process",
        "Defense Impairment",
    ),
    t(
        "T1556.001",
        "Domain Controller Authentication",
        "Defense Impairment",
    ),
    t("T1556.002", "Password Filter DLL", "Defense Impairment"),
    t(
        "T1556.003",
        "Pluggable Authentication Modules",
        "Defense Impairment",
    ),
    t(
        "T1556.004",
        "Network Device Authentication",
        "Defense Impairment",
    ),
    t("T1556.005", "Reversible Encryption", "Defense Impairment"),
    t(
        "T1556.006",
        "Multi-Factor Authentication",
        "Defense Impairment",
    ),
    t("T1556.007", "Hybrid Identity", "Defense Impairment"),
    t("T1556.008", "Network Provider DLL", "Defense Impairment"),
    t(
        "T1556.009",
        "Conditional Access Policies",
        "Defense Impairment",
    ),
    t(
        "T1578",
        "Modify Cloud Compute Infrastructure",
        "Defense Impairment",
    ),
    t("T1578.001", "Create Snapshot", "Defense Impairment"),
    t("T1578.002", "Create Cloud Instance", "Defense Impairment"),
    t("T1578.003", "Delete Cloud Instance", "Defense Impairment"),
    t("T1578.004", "Revert Cloud Instance", "Defense Impairment"),
    t(
        "T1578.005",
        "Modify Cloud Compute Configurations",
        "Defense Impairment",
    ),
    t("T1599", "Network Boundary Bridging", "Defense Impairment"),
    t(
        "T1599.001",
        "Network Address Translation Traversal",
        "Defense Impairment",
    ),
    t("T1600", "Weaken Encryption", "Defense Impairment"),
    t("T1600.001", "Reduce Key Space", "Defense Impairment"),
    t("T1600.002", "Disable Crypto Hardware", "Defense Impairment"),
    t("T1601", "Modify System Image", "Defense Impairment"),
    t("T1601.001", "Patch System Image", "Defense Impairment"),
    t("T1601.002", "Downgrade System Image", "Defense Impairment"),
    t("T1647", "Plist File Modification", "Defense Impairment"),
    t(
        "T1666",
        "Modify Cloud Resource Hierarchy",
        "Defense Impairment",
    ),
    t("T1685", "Disable or Modify Tools", "Defense Impairment"),
    t(
        "T1685.001",
        "Disable or Modify Windows Event Log",
        "Defense Impairment",
    ),
    t(
        "T1685.002",
        "Disable or Modify Cloud Log",
        "Defense Impairment",
    ),
    t("T1685.003", "Modify or Spoof Tool UI", "Defense Impairment"),
    t(
        "T1685.004",
        "Disable or Modify Linux Audit System Log",
        "Defense Impairment",
    ),
    t(
        "T1685.005",
        "Clear Windows Event Logs",
        "Defense Impairment",
    ),
    t(
        "T1685.006",
        "Clear Linux or Mac System Logs",
        "Defense Impairment",
    ),
    t(
        "T1686",
        "Disable or Modify System Firewall",
        "Defense Impairment",
    ),
    t("T1686.001", "Cloud Firewall", "Defense Impairment"),
    t("T1686.002", "Network Device Firewall", "Defense Impairment"),
    t("T1686.003", "Windows Host Firewall", "Defense Impairment"),
    t(
        "T1687",
        "Exploitation for Defense Impairment",
        "Defense Impairment",
    ),
    t("T1688", "Safe Mode Boot", "Defense Impairment"),
    t("T1689", "Downgrade Attack", "Defense Impairment"),
    t(
        "T1690",
        "Prevent Command History Logging",
        "Defense Impairment",
    ),
    // ---- Credential Access ----
    t("T1003", "OS Credential Dumping", "Credential Access"),
    t("T1003.001", "LSASS Memory", "Credential Access"),
    t("T1003.002", "Security Account Manager", "Credential Access"),
    t("T1003.003", "NTDS", "Credential Access"),
    t("T1003.004", "LSA Secrets", "Credential Access"),
    t(
        "T1003.005",
        "Cached Domain Credentials",
        "Credential Access",
    ),
    t("T1003.006", "DCSync", "Credential Access"),
    t("T1003.007", "Proc Filesystem", "Credential Access"),
    t(
        "T1003.008",
        "/etc/passwd and /etc/shadow",
        "Credential Access",
    ),
    t("T1040", "Network Sniffing", "Credential Access"),
    t("T1056", "Input Capture", "Credential Access"),
    t("T1056.001", "Keylogging", "Credential Access"),
    t("T1056.002", "GUI Input Capture", "Credential Access"),
    t("T1056.003", "Web Portal Capture", "Credential Access"),
    t("T1056.004", "Credential API Hooking", "Credential Access"),
    t("T1110", "Brute Force", "Credential Access"),
    t("T1110.001", "Password Guessing", "Credential Access"),
    t("T1110.002", "Password Cracking", "Credential Access"),
    t("T1110.003", "Password Spraying", "Credential Access"),
    t("T1110.004", "Credential Stuffing", "Credential Access"),
    t(
        "T1111",
        "Multi-Factor Authentication Interception",
        "Credential Access",
    ),
    t("T1187", "Forced Authentication", "Credential Access"),
    t(
        "T1212",
        "Exploitation for Credential Access",
        "Credential Access",
    ),
    t(
        "T1528",
        "Steal Application Access Token",
        "Credential Access",
    ),
    t("T1539", "Steal Web Session Cookie", "Credential Access"),
    t("T1552", "Unsecured Credentials", "Credential Access"),
    t("T1552.001", "Credentials In Files", "Credential Access"),
    t("T1552.002", "Credentials in Registry", "Credential Access"),
    t("T1552.003", "Shell History", "Credential Access"),
    t("T1552.004", "Private Keys", "Credential Access"),
    t(
        "T1552.005",
        "Cloud Instance Metadata API",
        "Credential Access",
    ),
    t("T1552.006", "Group Policy Preferences", "Credential Access"),
    t("T1552.007", "Container API", "Credential Access"),
    t("T1552.008", "Chat Messages", "Credential Access"),
    t(
        "T1555",
        "Credentials from Password Stores",
        "Credential Access",
    ),
    t("T1555.001", "Keychain", "Credential Access"),
    t("T1555.002", "Securityd Memory", "Credential Access"),
    t(
        "T1555.003",
        "Credentials from Web Browsers",
        "Credential Access",
    ),
    t(
        "T1555.004",
        "Windows Credential Manager",
        "Credential Access",
    ),
    t("T1555.005", "Password Managers", "Credential Access"),
    t(
        "T1555.006",
        "Cloud Secrets Management Stores",
        "Credential Access",
    ),
    t(
        "T1556",
        "Modify Authentication Process",
        "Credential Access",
    ),
    t(
        "T1556.001",
        "Domain Controller Authentication",
        "Credential Access",
    ),
    t("T1556.002", "Password Filter DLL", "Credential Access"),
    t(
        "T1556.003",
        "Pluggable Authentication Modules",
        "Credential Access",
    ),
    t(
        "T1556.004",
        "Network Device Authentication",
        "Credential Access",
    ),
    t("T1556.005", "Reversible Encryption", "Credential Access"),
    t(
        "T1556.006",
        "Multi-Factor Authentication",
        "Credential Access",
    ),
    t("T1556.007", "Hybrid Identity", "Credential Access"),
    t("T1556.008", "Network Provider DLL", "Credential Access"),
    t(
        "T1556.009",
        "Conditional Access Policies",
        "Credential Access",
    ),
    t("T1557", "Adversary-in-the-Middle", "Credential Access"),
    t(
        "T1557.001",
        "Name Resolution Poisoning and SMB Relay",
        "Credential Access",
    ),
    t("T1557.002", "ARP Cache Poisoning", "Credential Access"),
    t("T1557.003", "DHCP Spoofing", "Credential Access"),
    t("T1557.004", "Evil Twin", "Credential Access"),
    t(
        "T1558",
        "Steal or Forge Kerberos Tickets",
        "Credential Access",
    ),
    t("T1558.001", "Golden Ticket", "Credential Access"),
    t("T1558.002", "Silver Ticket", "Credential Access"),
    t("T1558.003", "Kerberoasting", "Credential Access"),
    t("T1558.004", "AS-REP Roasting", "Credential Access"),
    t("T1558.005", "Ccache Files", "Credential Access"),
    t("T1606", "Forge Web Credentials", "Credential Access"),
    t("T1606.001", "Web Cookies", "Credential Access"),
    t("T1606.002", "SAML Tokens", "Credential Access"),
    t(
        "T1621",
        "Multi-Factor Authentication Request Generation",
        "Credential Access",
    ),
    t(
        "T1649",
        "Steal or Forge Authentication Certificates",
        "Credential Access",
    ),
    // ---- Discovery ----
    t("T1007", "System Service Discovery", "Discovery"),
    t("T1010", "Application Window Discovery", "Discovery"),
    t("T1012", "Query Registry", "Discovery"),
    t(
        "T1016",
        "System Network Configuration Discovery",
        "Discovery",
    ),
    t("T1016.001", "Internet Connection Discovery", "Discovery"),
    t("T1016.002", "Wi-Fi Discovery", "Discovery"),
    t("T1018", "Remote System Discovery", "Discovery"),
    t("T1033", "System Owner/User Discovery", "Discovery"),
    t("T1040", "Network Sniffing", "Discovery"),
    t("T1046", "Network Service Discovery", "Discovery"),
    t("T1049", "System Network Connections Discovery", "Discovery"),
    t("T1057", "Process Discovery", "Discovery"),
    t("T1069", "Permission Groups Discovery", "Discovery"),
    t("T1069.001", "Local Groups", "Discovery"),
    t("T1069.002", "Domain Groups", "Discovery"),
    t("T1069.003", "Cloud Groups", "Discovery"),
    t("T1082", "System Information Discovery", "Discovery"),
    t("T1083", "File and Directory Discovery", "Discovery"),
    t("T1087", "Account Discovery", "Discovery"),
    t("T1087.001", "Local Account", "Discovery"),
    t("T1087.002", "Domain Account", "Discovery"),
    t("T1087.003", "Email Account", "Discovery"),
    t("T1087.004", "Cloud Account", "Discovery"),
    t("T1120", "Peripheral Device Discovery", "Discovery"),
    t("T1124", "System Time Discovery", "Discovery"),
    t("T1135", "Network Share Discovery", "Discovery"),
    t("T1201", "Password Policy Discovery", "Discovery"),
    t("T1217", "Browser Information Discovery", "Discovery"),
    t("T1482", "Domain Trust Discovery", "Discovery"),
    t("T1497", "Virtualization/Sandbox Evasion", "Discovery"),
    t("T1497.001", "System Checks", "Discovery"),
    t("T1497.002", "User Activity Based Checks", "Discovery"),
    t("T1497.003", "Time Based Checks", "Discovery"),
    t("T1518", "Software Discovery", "Discovery"),
    t("T1518.001", "Security Software Discovery", "Discovery"),
    t("T1518.002", "Backup Software Discovery", "Discovery"),
    t("T1526", "Cloud Service Discovery", "Discovery"),
    t("T1538", "Cloud Service Dashboard", "Discovery"),
    t("T1580", "Cloud Infrastructure Discovery", "Discovery"),
    t("T1613", "Container and Resource Discovery", "Discovery"),
    t("T1614", "System Location Discovery", "Discovery"),
    t("T1614.001", "System Language Discovery", "Discovery"),
    t("T1615", "Group Policy Discovery", "Discovery"),
    t("T1619", "Cloud Storage Object Discovery", "Discovery"),
    t("T1622", "Debugger Evasion", "Discovery"),
    t("T1652", "Device Driver Discovery", "Discovery"),
    t("T1654", "Log Enumeration", "Discovery"),
    t("T1673", "Virtual Machine Discovery", "Discovery"),
    t("T1680", "Local Storage Discovery", "Discovery"),
    // ---- Lateral Movement ----
    t("T1021", "Remote Services", "Lateral Movement"),
    t("T1021.001", "Remote Desktop Protocol", "Lateral Movement"),
    t("T1021.002", "SMB/Windows Admin Shares", "Lateral Movement"),
    t(
        "T1021.003",
        "Distributed Component Object Model",
        "Lateral Movement",
    ),
    t("T1021.004", "SSH", "Lateral Movement"),
    t("T1021.005", "VNC", "Lateral Movement"),
    t("T1021.006", "Windows Remote Management", "Lateral Movement"),
    t("T1021.007", "Cloud Services", "Lateral Movement"),
    t(
        "T1021.008",
        "Direct Cloud VM Connections",
        "Lateral Movement",
    ),
    t("T1072", "Software Deployment Tools", "Lateral Movement"),
    t("T1080", "Taint Shared Content", "Lateral Movement"),
    t(
        "T1091",
        "Replication Through Removable Media",
        "Lateral Movement",
    ),
    t(
        "T1210",
        "Exploitation of Remote Services",
        "Lateral Movement",
    ),
    t("T1534", "Internal Spearphishing", "Lateral Movement"),
    t(
        "T1550",
        "Use Alternate Authentication Material",
        "Lateral Movement",
    ),
    t("T1550.001", "Application Access Token", "Lateral Movement"),
    t("T1550.002", "Pass the Hash", "Lateral Movement"),
    t("T1550.003", "Pass the Ticket", "Lateral Movement"),
    t("T1550.004", "Web Session Cookie", "Lateral Movement"),
    t(
        "T1563",
        "Remote Service Session Hijacking",
        "Lateral Movement",
    ),
    t("T1563.001", "SSH Hijacking", "Lateral Movement"),
    t("T1563.002", "RDP Hijacking", "Lateral Movement"),
    t("T1570", "Lateral Tool Transfer", "Lateral Movement"),
    // ---- Collection ----
    t("T1005", "Data from Local System", "Collection"),
    t("T1025", "Data from Removable Media", "Collection"),
    t("T1039", "Data from Network Shared Drive", "Collection"),
    t("T1056", "Input Capture", "Collection"),
    t("T1056.001", "Keylogging", "Collection"),
    t("T1056.002", "GUI Input Capture", "Collection"),
    t("T1056.003", "Web Portal Capture", "Collection"),
    t("T1056.004", "Credential API Hooking", "Collection"),
    t("T1074", "Data Staged", "Collection"),
    t("T1074.001", "Local Data Staging", "Collection"),
    t("T1074.002", "Remote Data Staging", "Collection"),
    t("T1113", "Screen Capture", "Collection"),
    t("T1114", "Email Collection", "Collection"),
    t("T1114.001", "Local Email Collection", "Collection"),
    t("T1114.002", "Remote Email Collection", "Collection"),
    t("T1114.003", "Email Forwarding Rule", "Collection"),
    t("T1115", "Clipboard Data", "Collection"),
    t("T1119", "Automated Collection", "Collection"),
    t("T1123", "Audio Capture", "Collection"),
    t("T1125", "Video Capture", "Collection"),
    t("T1185", "Browser Session Hijacking", "Collection"),
    t("T1213", "Data from Information Repositories", "Collection"),
    t("T1213.001", "Confluence", "Collection"),
    t("T1213.002", "Sharepoint", "Collection"),
    t("T1213.003", "Code Repositories", "Collection"),
    t(
        "T1213.004",
        "Customer Relationship Management Software",
        "Collection",
    ),
    t("T1213.005", "Messaging Applications", "Collection"),
    t("T1213.006", "Databases", "Collection"),
    t("T1530", "Data from Cloud Storage", "Collection"),
    t("T1557", "Adversary-in-the-Middle", "Collection"),
    t(
        "T1557.001",
        "Name Resolution Poisoning and SMB Relay",
        "Collection",
    ),
    t("T1557.002", "ARP Cache Poisoning", "Collection"),
    t("T1557.003", "DHCP Spoofing", "Collection"),
    t("T1557.004", "Evil Twin", "Collection"),
    t("T1560", "Archive Collected Data", "Collection"),
    t("T1560.001", "Archive via Utility", "Collection"),
    t("T1560.002", "Archive via Library", "Collection"),
    t("T1560.003", "Archive via Custom Method", "Collection"),
    t("T1602", "Data from Configuration Repository", "Collection"),
    t("T1602.001", "SNMP (MIB Dump)", "Collection"),
    t(
        "T1602.002",
        "Network Device Configuration Dump",
        "Collection",
    ),
    // ---- Command and Control ----
    t("T1001", "Data Obfuscation", "Command and Control"),
    t("T1001.001", "Junk Data", "Command and Control"),
    t("T1001.002", "Steganography", "Command and Control"),
    t(
        "T1001.003",
        "Protocol or Service Impersonation",
        "Command and Control",
    ),
    t("T1008", "Fallback Channels", "Command and Control"),
    t("T1071", "Application Layer Protocol", "Command and Control"),
    t("T1071.001", "Web Protocols", "Command and Control"),
    t(
        "T1071.002",
        "File Transfer Protocols",
        "Command and Control",
    ),
    t("T1071.003", "Mail Protocols", "Command and Control"),
    t("T1071.004", "DNS", "Command and Control"),
    t(
        "T1071.005",
        "Publish/Subscribe Protocols",
        "Command and Control",
    ),
    t("T1090", "Proxy", "Command and Control"),
    t("T1090.001", "Internal Proxy", "Command and Control"),
    t("T1090.002", "External Proxy", "Command and Control"),
    t("T1090.003", "Multi-hop Proxy", "Command and Control"),
    t("T1090.004", "Domain Fronting", "Command and Control"),
    t(
        "T1092",
        "Communication Through Removable Media",
        "Command and Control",
    ),
    t(
        "T1095",
        "Non-Application Layer Protocol",
        "Command and Control",
    ),
    t("T1102", "Web Service", "Command and Control"),
    t("T1102.001", "Dead Drop Resolver", "Command and Control"),
    t(
        "T1102.002",
        "Bidirectional Communication",
        "Command and Control",
    ),
    t("T1102.003", "One-Way Communication", "Command and Control"),
    t("T1104", "Multi-Stage Channels", "Command and Control"),
    t("T1105", "Ingress Tool Transfer", "Command and Control"),
    t("T1132", "Data Encoding", "Command and Control"),
    t("T1132.001", "Standard Encoding", "Command and Control"),
    t("T1132.002", "Non-Standard Encoding", "Command and Control"),
    t("T1205", "Traffic Signaling", "Command and Control"),
    t("T1205.001", "Port Knocking", "Command and Control"),
    t("T1205.002", "Socket Filters", "Command and Control"),
    t("T1219", "Remote Access Tools", "Command and Control"),
    t("T1219.001", "IDE Tunneling", "Command and Control"),
    t(
        "T1219.002",
        "Remote Desktop Software",
        "Command and Control",
    ),
    t("T1219.003", "Remote Access Hardware", "Command and Control"),
    t("T1568", "Dynamic Resolution", "Command and Control"),
    t("T1568.001", "Fast Flux DNS", "Command and Control"),
    t(
        "T1568.002",
        "Domain Generation Algorithms",
        "Command and Control",
    ),
    t("T1568.003", "DNS Calculation", "Command and Control"),
    t("T1571", "Non-Standard Port", "Command and Control"),
    t("T1572", "Protocol Tunneling", "Command and Control"),
    t("T1573", "Encrypted Channel", "Command and Control"),
    t("T1573.001", "Symmetric Cryptography", "Command and Control"),
    t(
        "T1573.002",
        "Asymmetric Cryptography",
        "Command and Control",
    ),
    t("T1659", "Content Injection", "Command and Control"),
    t("T1665", "Hide Infrastructure", "Command and Control"),
    // ---- Exfiltration ----
    t(
        "T1011",
        "Exfiltration Over Other Network Medium",
        "Exfiltration",
    ),
    t("T1011.001", "Exfiltration Over Bluetooth", "Exfiltration"),
    t("T1020", "Automated Exfiltration", "Exfiltration"),
    t("T1020.001", "Traffic Duplication", "Exfiltration"),
    t("T1029", "Scheduled Transfer", "Exfiltration"),
    t("T1030", "Data Transfer Size Limits", "Exfiltration"),
    t("T1041", "Exfiltration Over C2 Channel", "Exfiltration"),
    t(
        "T1048",
        "Exfiltration Over Alternative Protocol",
        "Exfiltration",
    ),
    t(
        "T1048.001",
        "Exfiltration Over Symmetric Encrypted Non-C2 Protocol",
        "Exfiltration",
    ),
    t(
        "T1048.002",
        "Exfiltration Over Asymmetric Encrypted Non-C2 Protocol",
        "Exfiltration",
    ),
    t(
        "T1048.003",
        "Exfiltration Over Unencrypted Non-C2 Protocol",
        "Exfiltration",
    ),
    t("T1052", "Exfiltration Over Physical Medium", "Exfiltration"),
    t("T1052.001", "Exfiltration over USB", "Exfiltration"),
    t("T1537", "Transfer Data to Cloud Account", "Exfiltration"),
    t("T1567", "Exfiltration Over Web Service", "Exfiltration"),
    t(
        "T1567.001",
        "Exfiltration to Code Repository",
        "Exfiltration",
    ),
    t("T1567.002", "Exfiltration to Cloud Storage", "Exfiltration"),
    t(
        "T1567.003",
        "Exfiltration to Text Storage Sites",
        "Exfiltration",
    ),
    t("T1567.004", "Exfiltration Over Webhook", "Exfiltration"),
    // ---- Impact ----
    t("T1485", "Data Destruction", "Impact"),
    t("T1485.001", "Lifecycle-Triggered Deletion", "Impact"),
    t("T1486", "Data Encrypted for Impact", "Impact"),
    t("T1489", "Service Stop", "Impact"),
    t("T1490", "Inhibit System Recovery", "Impact"),
    t("T1491", "Defacement", "Impact"),
    t("T1491.001", "Internal Defacement", "Impact"),
    t("T1491.002", "External Defacement", "Impact"),
    t("T1495", "Firmware Corruption", "Impact"),
    t("T1496", "Resource Hijacking", "Impact"),
    t("T1496.001", "Compute Hijacking", "Impact"),
    t("T1496.002", "Bandwidth Hijacking", "Impact"),
    t("T1496.003", "SMS Pumping", "Impact"),
    t("T1496.004", "Cloud Service Hijacking", "Impact"),
    t("T1498", "Network Denial of Service", "Impact"),
    t("T1498.001", "Direct Network Flood", "Impact"),
    t("T1498.002", "Reflection Amplification", "Impact"),
    t("T1499", "Endpoint Denial of Service", "Impact"),
    t("T1499.001", "OS Exhaustion Flood", "Impact"),
    t("T1499.002", "Service Exhaustion Flood", "Impact"),
    t("T1499.003", "Application Exhaustion Flood", "Impact"),
    t("T1499.004", "Application or System Exploitation", "Impact"),
    t("T1529", "System Shutdown/Reboot", "Impact"),
    t("T1531", "Account Access Removal", "Impact"),
    t("T1561", "Disk Wipe", "Impact"),
    t("T1561.001", "Disk Content Wipe", "Impact"),
    t("T1561.002", "Disk Structure Wipe", "Impact"),
    t("T1565", "Data Manipulation", "Impact"),
    t("T1565.001", "Stored Data Manipulation", "Impact"),
    t("T1565.002", "Transmitted Data Manipulation", "Impact"),
    t("T1565.003", "Runtime Data Manipulation", "Impact"),
    t("T1657", "Financial Theft", "Impact"),
    t("T1667", "Email Bombing", "Impact"),
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn no_duplicate_id_tactic_pairs() {
        let mut pairs: Vec<(&str, &str)> = TTP_CATALOG.iter().map(|d| (d.id, d.tactic)).collect();
        let before = pairs.len();
        pairs.sort();
        pairs.dedup();
        assert_eq!(
            before,
            pairs.len(),
            "duplicate (id, tactic) pairs in TTP catalog"
        );
    }

    #[test]
    fn covers_full_enterprise_matrix() {
        // Sanity check: the full MITRE ATT&CK enterprise matrix (techniques +
        // sub-techniques, current 15-tactic taxonomy) is in the 800s; this
        // guards against an accidental truncation regressing the catalog
        // back to the old hand-picked ~150-entry subset.
        assert!(
            TTP_CATALOG.len() > 800,
            "expected the full ATT&CK matrix, got {} entries",
            TTP_CATALOG.len()
        );
    }

    #[test]
    fn every_id_starts_with_t_and_every_field_is_non_empty() {
        for def in TTP_CATALOG {
            assert!(def.id.starts_with('T'), "bad id: {}", def.id);
            assert!(!def.name.is_empty(), "empty name for {}", def.id);
            assert!(!def.tactic.is_empty(), "empty tactic for {}", def.id);
        }
    }
}
